### DISCUSSION TITLE
请问一下paopaodns和adguardhome怎么配置呢

### DISCUSSION THREAD

**Discussion by sunshinehcyyy** [kkkgo/PaoPaoDNS#146] [问答和帮助] [answered]
想要用ADguardhome 的功能以及管理dns信息，请问一下怎么搞呢？
PVE虚拟ikuai+ppgw
ikuai 10.0.0.1，dns10.0.1.2
ppgw 10.0.0.2，dns10.0.1.2
paopaodns通过ikuai内置的docker搭建，地址是10.0.1.3
adguardhome 也是ikuai的docker搭建的，地址是10.0.1.2，在dns设置里面填写上游dns唯一值是10.0.1.3，目前看日志确实是通过paopao解析的。但是没法上外网。
i快的静态路由填写上没有什么用的。

**Comment by kkkgo** [comment, marked as answer]
你的提问跟adguardhome也没啥关系，你把paopaodns+ppgw调通了就行了，adguardhome无非就是多套一层上游。
可以参考讨论区教程： https://github.com/kkkgo/PaoPaoGateWay/discussions/categories/%E9%85%8D%E7%BD%AE%E5%88%86%E4%BA%AB

**Reply by sunshinehcyyy** [reply]
谢谢大佬回复，请问一下如果我调通了dns和gw之后，应该怎么加入adguardhome呢。我搜了一下，没有搜到。

**Reply by kkkgo** [reply]
无非就是把你的adguardhome上游设置为paopaodns，没了。

**Reply by sunshinehcyyy** [reply]
ppgw和adguardhome我搭建成了，现在就是paopaoDNS有点问题，主要是我不想在PVE弄CT模板跑docker，目前用的是pve下ikuai自带的docker跑的adg和paopaodns。
现在我直接网关指向ppgw能用，但是dns我输入test.sh就全错。我再研究一下。

**Reply by kkkgo** [reply]
设备直接网关指向ppgw相当于全局代理，一般不会这么设置

**Reply by sunshinehcyyy** [reply]
就是不想要全局代理才折腾这些的，已经放弃用ikuai自带的docker跑dns了，准备用ct跑了。

**Reply by kiss2u** [reply]
@kkkgo 大佬 咨询一下，在fakeip模式下，adguardhome 有无必要开启cache？就是fakeip每次分配的ip对应地址是固定的还是随机的？比如google.com  是不是始终分配的是1.1.1.1，如果下次变成了 1.1.1.2，那开了cache反而是帮倒忙了。

**Reply by kkkgo** [reply]
fakeip你只要不重启虚拟机都是固定的。如果你定制镜像sniff=yes的话，就算重启了不对应也能用。
fakeip就是你指定的CIDR内按顺序分配，比如你指定7.0.0.0/8，第一个请求的域名是google.com，就会给google.com分配7.0.0.1。
开cache无问题的，只要遵守ttl，实际上效果理论上不会有区别（如果你改了一些分流规则之类，那可能要等ttl过期后才生效），还可以减少请求次数，除非你开adguardhome的乐观缓存，乐观缓存这个是不遵守ttl的。

**Reply by kiss2u** [reply]
@kkkgo 感谢大佬解释，在sniff=yes的情况下，ttl设置多少为宜？我看到ppdns是默认为0，那最佳设置是不是也是为0？

**Reply by kkkgo** [reply]
如果你是指CUSTOM_FORWARD_TTL的话，这是一个自定义选项，大于0才会生效，设置为0的话就不改变原来的ttl，也就是转发过来的ttl是多少就是多少（在ppgw的情况下，这个值就取决于clash核心，FakeIP一般提供的是`1~3`的ttl）。 
为了FakeIP在发生变化后能及时改变，ttl值一般都很低，这也是为了避免重启网关修改设置等操作导致不生效。
如果你的网关长期不用重启，设置稍长的ttl可以减少DNS查询请求的发起，比如`60~600`内（`1~10`分钟）。在sniff=yes的情况下，FakeIP对不上也可以兼容http/https协议，作为ttl期间的过渡可以降低故障切换的影响感知。

**Comment by xingshu1990** [comment]
// 05-22更新 GPT多出来个 UPSTREAM_DNS,
// 作者告知没这个东西 遂删除。

我这边用docker-compose跑的adguardhome和paopaodns。
另小声说下我的搭建情况
>补充：我使用的是raspberry 3B+，装的是Raspberry Pi OS（Bookworm)
系统本身自带的DNS服务会占用53端口，
树莓派环境下，如果第一时间没有其他底层代码的操作，或者其他DNS服务的安装，
默认是systemd-resolved在占用53，
输入sudo netstat -tuln | grep 53可查询53端口占用情况。

>以下两个分别是取消和禁用
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
等几秒以后输入sudo netstat -tuln | grep 53，
发现无程序在占用53端口的话
就可以启用docker了。

>因为上面停止及禁用systemd-resolved
>本身/etc/resolv.conf里面设置的DNS为127.0.0.1，
>每次执行docker-compose down
>编辑docker-compose.yml文件
>执行sudo docker-compose up -d都返回没有网络

>遂手动在/etc/resolv.conf新添加了nameserver 223.5.5.5 和nameserver 8.8.8.8
>我是按照这个链接里的docker配置，丢给chatgpt3.5帮我配置的
>https://www.jackiewu.top/45fe9747966b48f5a4b9ec08fb1fdd80?pvs=25
>另外paopaodns不是处理科学上网的事情的。

## 丢一个docker-compose的配置 ##
```
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /home/pi/workdir:/opt/adguardhome/work     
      - /home/pi/confdir:/opt/adguardhome/conf     
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "6060:6060/tcp"
    environment:
      - TZ=Your/Timezone

  paopaodns:
    image: sliamb/paopaodns:latest
    container_name: paopaodns
    volumes:
      - /home/pi/mydata:/data
    environment:
      - CNAUTO=yes
      - USE_MARK_DATA=yes
      - CNFALL=yes
      - IPV6=no
      - RULES_TTL=604800
      - SHUFFLE=yes
      - ADDINFO=yes
    restart: always
    ports:
      - "54:53/tcp"
      - "54:53/udp"

```
paopaodns搭建和测试成功与否，我这里不详说了，

然后通过web访问搭建adguardhome的ip:3000，安装adguardhome，
在adguardhome里上游服务器里输入：
tcp://{paopaodns的IP}:端口
例如tcp://192.168.1.235:54

点击下方的应用、测试上游，
如果WEB界面右下角快速弹出【上游服务器保存成功】【指定的 DNS 服务器现已正常运行】
那么paopaodns在正常运行。
