### DISCUSSION TITLE
iKuai+PaoPaoDNS+UPCG+SingBox配置分享

### DISCUSSION THREAD

**Discussion by hackerlengyue** [kkkgo/PaoPaoDNS#151] [经验分享]
# 一、配置说明
以下使用Pve进行配置
主路由：ikuai
DNS：PaoPaoDNS
配置界面：UPCG
网关：SingBox
# 二、开始配置
## 2.1 PaoPaoDNS
地址：192.168.6.5
Pve下使用CT容器，我喜欢用乌班图的，你喜欢啥就用啥，这个随意
### 2.2.1 安装docker
首先安装docker，命令如下
```shell
sudo curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
```
设置开机自启：
```shell
systemctl enable docker.service --now
```
### 2.2.1 安装PaoPaoDNS
创建一个文件夹，你想创建哪里就创建哪里，我喜欢data下

```shell
mkdir -p /data/paopaodns
```
创建docker-compose.yml文件，命令如下：

```shell
vi docker-compose.yml
```
按i进行编辑
paopaodns配置如下

其中- CUSTOM_FORWARD=192.168.6.6:53的192.168.6.6为singbox所在ip地址。

```yml
version: '3'

services:
  paopaodns:
    image: sliamb/paopaodns:latest
    container_name: paopaodns
    restart: unless-stopped
    volumes:
      - /home/mydata:/data
    environment:
      - UPDATE=weekly
      - CNAUTO=yes
      - CNFALL=yes
      - CN_TRACKER=yes
      - IPV6=no
      - CUSTOM_FORWARD=192.168.6.6:53
      - AUTO_FORWARD=yes
      - AUTO_FORWARD_CHECK=yes
      - USE_MARK_DATA=yes
      - CN_TRACKER=yes
      - ADDINFO=no
      - SHUFFLE=yes
      - RULES_TTL=604800
      - TZ=Asia/Shanghai
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5304:5304/tcp"
      - "5304:5304/udp"
```
然后按esc输入:wq保存。

执行创建命令
```shell
docker compose up -d
```

## 2.2 UPCG+SingBox
地址：192.168.6.6
Pve下使用CT容器，我喜欢用乌班图的，你喜欢啥就用啥，这个随意。

下载UPCG作者提供的安装包，执行解压命令

```shell
unzip 文件名
```
进入文件，执行安装脚本，命令如下：
```shell
./install.sh
```
访问地址：http://192.168.6.6:8080/upcg/ 用浏览器打开哈，就可进入配置页面。（yacd和metaui可直接在upcg中跳转）

![截屏2024-05-27 11 42 43](https://github.com/kkkgo/PaoPaoDNS/assets/59858726/f5fb22b7-e417-422f-bfca-8f817a86d702)

视频使用教程：https://youtu.be/_zVSz7QMpwM?si=KZyg3tYjhfmTufVP

记得勾选fakeip哈

![截屏2024-05-27 11 45 25](https://github.com/kkkgo/PaoPaoDNS/assets/59858726/90f4d050-ffeb-448c-a426-b57207d73854)

### 2.3.1 静态路由
首先设置静态路由，先下载txt文件，然后导入。
文件：
[static_route.txt](https://github.com/kkkgo/PaoPaoDNS/files/15450850/static_route.txt)

图：
![截屏2024-05-27 12 33 02](https://github.com/kkkgo/PaoPaoDNS/assets/59858726/f99ea0d2-b53d-46bf-9ebe-db063fcce768)

### 2.3.1 设置dhcp
根据图片进行设置
![截屏2024-05-27 12 49 07](https://github.com/kkkgo/PaoPaoDNS/assets/59858726/ecc57b25-e09f-4098-9b82-07e212383eb9)

# 三、总结
总体上比较简单，upcg极大的方便了配置并且配合singbox整体是非常舒服的。
我测试了几天非常的稳定，目前没发现奇怪的问题。
