### DISCUSSION TITLE
树莓派 3B+ 利用docker-compose 单台设备安装paopaodns adguardhome

### DISCUSSION THREAD

**Discussion by xingshu1990** [kkkgo/PaoPaoDNS#152] [经验分享]
树莓派3B+ 1G的内存，4 x [USB 2.0接口]
常规配置，同ipad一样，是常见的吃灰设备之一。

树莓派环境为：Raspberry Pi OS Lite 
Release date: March 15th 2024
System: 32-bit
Kernel version: 6.6
Debian version: 12 (bookworm)

下载连接：https://downloads.raspberrypi.com/raspios_lite_armhf/images/raspios_lite_armhf-2024-03-15/2024-03-15-raspios-bookworm-armhf-lite.img.xz

----

本文默认认为你已经在使用科学上网，并且可以安装proxychains，
给wget、curl等软件使用科学上网。

这里不讲解docker、docker-compose的安装和使用，
docker-compose是独立安装，非docker自带的docker compose

----

先直接在树莓派里输入
sudo netstat -tuln | grep :53
你会发现大概类似下面这样的内容。

我已经成功运行adguardhome和paopaodns，所以是下面的内容。
部分有困难焦虑的人士，看到数据和你树莓派上的不一样，这个不要焦虑。
![QQ截图20240601123238](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/fa85aeb2-7248-442b-b085-2f4e7f092a9a)

----
我的树莓派全新烧录img后，
占用53端口的是systemd-resolved，
> systemd-resolved：主要负责网络连接的管理和域名解析。简单来说，systemd-resolved就是用来管理网络连接和DNS解析的。

于是分别输入以下命令，用以取消和禁用systemd-resolved服务：
```
sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved
```
然后你会发现，你没网络了。
不着急。继续往下看。

----

接着输入sudo nano /etc/resolve.conf
按照下图加入223.5.5.5和8.8.8.8，稍后用到。

在能正常运行paopaodns以后，这里还得修改为：
nameserver 127.0.0.1（也可能paopaodns自动修改）
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/b364ab7b-6136-42ec-99c1-83ba9f521b18)

docker-compose代码参考：https://www.jackiewu.top/45fe9747966b48f5a4b9ec08fb1fdd80?pvs=25
于是按照上面网址内的内容，AdGuardHome 为53端口，paopaodns为54端口，
直接把docker代码丢给chatgpt让其改写成docker-compose，代码如下，
**注意，自行创建/修改volumes中的宿主机目录**，以及paopaodns，environment下的功能，还有端口：

在你存放docker-compose.yml的地方，输入sudo nano docker-compose.yml

复制下方的内容到 yml文件里，保存。
```
services:
  # AdGuardHome 服务
  adguardhome:
    # 使用 AdGuardHome 的最新版本镜像
    image: adguard/adguardhome:latest
    # 容器名称
    container_name: adguardhome
    # 重启策略：除非停止运行
    restart: unless-stopped
    # 挂载卷配置
    volumes:
      # 将宿主机的 /home/pi/workdir 挂载到容器的 /opt/adguardhome/work
      - /home/pi/workdir:/opt/adguardhome/work
      # 将宿主机的 /home/pi/confdir 挂载到容器的 /opt/adguardhome/conf
      - /home/pi/confdir:/opt/adguardhome/conf

    # 端口映射配置
    ports:
      # TCP/UDP 端口映射：宿主机的 53 端口映射到容器的 53 端口
      - "53:53/tcp"
      - "53:53/udp"
      # 其他端口映射...
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "6060:6060/tcp"

  # PaoPaoDNS 服务
  paopaodns:
    # 使用 PaoPaoDNS 的最新版本镜像
    image: sliamb/paopaodns:latest
    # 容器名称
    container_name: paopaodns
    # 挂载卷配置
    volumes:
      # 将宿主机的 /home/pi/mydata 挂载到容器的 /data
      - /home/pi/mydata:/data
    # 环境变量配置
    environment:
      # 时区设置为 Asia/Shanghai
      - TZ=Asia/Shanghai
      # DNS 服务器名称设置为 PaoPaoDNS,blog.03k.org
      - DNS_SERVERNAME=PaoPaoDNS,blog.03k.org
      # 启用中国大陆白名单
      - CNAUTO=yes
      # 使用 mark 数据
      - USE_MARK_DATA=yes
      # 启用中国大陆黑名单
      - CNFALL=yes
      # 禁用 IPv6
      - IPV6=no
      # 设置 SOCKS5 代理
      - SOCKS5=192.168.1.215:18188
      # 规则的 TTL 设置为 604800 秒（一周）
      - RULES_TTL=604800
      # 启用规则打乱
      - SHUFFLE=yes
      # 添加附加信息
      - ADDINFO=yes
      # 启用 HTTP 文件功能
      - HTTP_FILE=yes
    # 重启策略：始终重启
    restart: always
    # 端口映射配置
    ports:
      # TCP/UDP 端口映射：宿主机的 54 端口映射到容器的 53 端口
      - "54:53/tcp"
      - "54:53/udp"
      # 其他端口映射...
      - "5304:5304/udp"
      - "5304:5304/tcp"
      - "7889:7889/tcp"

```

然后保存，

这里提一下，如果树莓派，或者你当前在装的设备的上一层设备没有科学上网
（给小白：你就理解成从上一路由器里的LAN口接出来，接入到当前设备WAN口给当前设备提供网络）
但是在局域网内某个win设备上装了科学上网，并且有socks和http，
那么以树莓派3B+举例：

#创建目录
```
sudo mkdir -p /etc/systemd/system/docker.service.d
sudo nano /etc/systemd/system/docker.service.d/proxy.conf
```

内容参考下图，
改动的是http_proxy 和https_proxy这两个部分
![QQ截图20240615091149](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/3e06d038-4326-4ec6-aa2d-07497fc7fa9a)
然后重新加载系统的 systemd 配置并重启 Docker 服务：
```
sudo systemctl daemon-reload
sudo systemctl restart docker
```
这个时候，你的docker 或者docker-compose已经可以使用科学上网了
这样就可以很方便的使用sudo docker-compose pull

科学上网软件为：V2RAYN，
其软件里的DNS设置为：
```
{
 "servers": [
  {
   "address": "https://1.1.1.1/dns-query",
 "domains": [
        "domain:youtube.com","domain:www.bing.com","chromewebstore.google.com",
        "geosite:geolocation-!cn",
        "geosite:github",
        "geosite:google",
        "geosite:youtube","www.wszf.me","nextdns.io",
        "github.com"
      ],
      "expectIPs": [
        "geoip:!cn"
      ]
    },
  {
   "address": "192.168.1.235",
      "port": 54,
   "domains": [
"geosite:cn","dns.weixin.qq.com.cn","tpass.zhejiang.chinatax.gov.cn",
        "ufo.baidu.com",
        "badjs.weixinbridge.com",
        "domain:baidu.com",
        "www.msn.cn"
   ],
   "expectIPs": [
    "geoip:cn","geoip:private"
   ]
  },
    "8.8.8.8",
    "9.9.9.9"
 ]
}
```

科学上网 DNS设置下方的Outbound Freedom domainStrategy为空，
域名解析笫略：Asls，域名匹配算法为空。

---

然后在当前目录里，非root账号中，输入sudo docker-compose up  或者sudo docker-compose up -d
首次运行的话，会下载、安装 镜像运行需要的库(由于上面配置了科学上网，现在速度不会慢，如果还是慢的话，查看是否配置有问题，或者节点不能联通)

注意，这里常见的错误是
在 Linux 系统中，要在没有使用 sudo 的情况下运行 Docker 和 Docker Compose，用户需要加入 docker 用户组。
直接输入sudo usermod -aG docker $USER

![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/f8b4ddda-7d3d-4d80-acd2-c2a2f7d1fe93)

一般有这两个数据，两个功能已经跑起来了
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/7eb30fb7-f977-40e0-ba53-53220b034d28)
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/e645bbf7-7d89-48a7-88b1-1e8736229d46)

---

然后浏览器输入192.168.1.*:3000，进入adguardhome的安装，
adguardhome的安装操作，我这里就不详细讲解了，网络上较多，
adguardhome DNS这里，如下填写
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/7a45af2b-2434-4e77-87c2-f313f852f0f5)

---

选择【并行请求】
先不管其他配置，直接先拉到这里点保存
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/86e21461-c293-4c38-9305-76ba37e078b8)

---

![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/cd3510df-8bb4-4383-aaf9-fce9422e8843)
依次点击保存、测试上游，右下角如图显示，说明能正常运行

adguardhome接下来的配置我直接放图，
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/0285b4ef-2135-4b13-9122-15c4f6f7eb28)
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/8b0e19e0-b480-4b5f-887e-9a87fba592dc)

#### 广告屏蔽规则部分
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/fc8d5f98-5310-4da5-aa08-365a2156b015)

#### adguardhome 用于科学上网解析广告规则等链接
这部分内容在 上述docker-compose配置里：/home/pi/confdir下的**AdGuardHome.yaml**里

![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/77c3dfcb-9358-4c54-bc0d-5a135f512d6e)

---

v2**yN中的geoip.dat 和 geosite.da文件，来源自：
https://github.com/Loyalsoldier/v2ray-rules-dat
下载到本地，停止科学上网后，手动复制到科学V2**yN文件夹里
重新运行软件。

---

以上这样配置后，paopaodns正常使用，adguardhome也能获取数据
![image](https://github.com/kkkgo/PaoPaoDNS/assets/18671173/fd77de7f-d5e4-479a-bb09-cfc6e1b39136)
科学上网平时也很流畅。

————————
06.15做了内容调整，增加了docker-compose科学上网部分的添加，以及一些语句顺序，词语的调整。
