### DISCUSSION TITLE
想问一下如果我在另一台服务器上搭建docker mihomo，我该怎么配置我的PaoPaoDNS

### DISCUSSION THREAD

**Discussion by xihazhiwang** [kkkgo/PaoPaoDNS#160] [问答和帮助] [answered]
现有网络环境：
本机地址：192.168.30.224/24，DNS：192.168.40.200，
虚拟机1:192.168.40.200（安装了adguardhome + ppdns）
虚拟机2:192.168.40.201（安装了docker mihomo 192.168.40.202）
192.168.40.0/24 和 192.168.30.0/24，主交换机设置了静态路由：198.18.0.0/255.255.0.0，可以互访，但是现在是可以访问内网，但是外网无法访问
虚拟机1docker-compose 配置：
```
version: "3.4"
services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - /root/adguardhome/work:/opt/adguardhome/work
      - /root/adguardhome/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "6060:6060/tcp"
    environment:
      - TZ=Asia/Shanghai

  paopaodns:
    image: sliamb/paopaodns:latest
    container_name: ppdns
    volumes:
      - /root/ppdns/data:/data
    environment:
      - CNAUTO=yes
      - USE_MARK_DATA=yes
      - CNFALL=yes
      - IPV6=no
      - RULES_TTL=604800
      - SHUFFLE=yes
      - ADDINFO=yes
      - CUSTOM_FORWARD=192.168.40.202:53
      - AUTO_FORWARD=yes
    restart: always
    ports:
      - "54:53/tcp"
      - "54:53/udp"
      - "5304:5304/tcp"
      - "5404:5304/udp"
```

虚拟机2docker-compose 配置：
```
version: "3"
services:
  mihomo:
    image: metacubex/mihomo
    container_name: mihomo
    networks:
      macvlan:
        ipv4_address: 192.168.40.202
    volumes:
      - /root/mihomo:/root/.config/mihomo/
    privileged: true
    restart: always
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      - TZ=Asia/Shanghai
networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
      macvlan_mode: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.1
```
mihomo config.yml
```
      url: http://www.gstatic.com/generate_204
proxy-groups:
"config.yaml" [readonly] 67263L, 3485411B                                                                                12,9          Top
allow-lan: true
mode: rule
log-level: info
ipv6: false
external-controller: '0.0.0.0:80'
external-ui: ui
secret: "password"
geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - tls://dns.alidns.com
    - https://dns.alidns.com/dns-query
    - tls://dot.pub
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - tls://1.0.0.1:853
    - https://cloudflare-dns.com/dns-query
    - tls://dns.google:853
    - https://dns.google/dns-query
  fallback:
    - tls://1.0.0.1:853
    - https://cloudflare-dns.com/dns-query
    - tls://dns.google:853
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
proxies:
```
是哪里设置的不对导致无法访问外网么
