### DISCUSSION TITLE
iKuai+PaoPaoDNS+Surge配置分享

### DISCUSSION THREAD

**Discussion by hackerlengyue** [kkkgo/PaoPaoDNS#161] [经验分享]
# 一、配置说明
以下使用Pve进行配置
主路由：ikuai
DNS：PaoPaoDNS
网关：Surge
# 二、开始配置
## 2.1 PaoPaoDNS
地址：192.168.6.5
Pve下使用CT容器，我喜欢用乌班图的，你喜欢啥就用啥，这个随意
### 2.2.1 安装docker
首先安装docker，命令如下
```shell
sudo curl -fsSL https://get.docker.com | bash -s docker --mirror Aliyun
```
设置开机自启：
```shell
systemctl enable docker.service --now
```
### 2.2.1 安装PaoPaoDNS
创建一个文件夹，你想创建哪里就创建哪里，我喜欢data下

```shell
mkdir -p /data/paopaodns
```
创建docker-compose.yml文件，命令如下：

```shell
vi docker-compose.yml
```
按i进行编辑
paopaodns配置如下

其中- CUSTOM_FORWARD=198.18.0.2:53的198.18.0.2为Surge的dns地址。

```yml
version: '3'

services:
  paopaodns:
    image: sliamb/paopaodns:latest
    container_name: paopaodns
    restart: unless-stopped
    volumes:
      - /home/mydata:/data
    environment:
      - UPDATE=weekly
      - CNAUTO=yes
      - CNFALL=yes
      - CN_TRACKER=yes
      - IPV6=no
      - CUSTOM_FORWARD=198.18.0.2:53
      - AUTO_FORWARD=yes
      - AUTO_FORWARD_CHECK=yes
      - USE_MARK_DATA=yes
      - CN_TRACKER=yes
      - ADDINFO=no
      - SHUFFLE=yes
      - RULES_TTL=604800
      - TZ=Asia/Shanghai
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5304:5304/tcp"
      - "5304:5304/udp"
```
然后按esc输入:wq保存。

执行创建命令
```shell
docker compose up -d
```

## 2.2 Surge
地址：192.168.6.6 
DNS：198.18.0.2

![截屏2024-06-24 11 17 38](https://github.com/kkkgo/PaoPaoDNS/assets/59858726/13f030a5-4af8-4ebc-b70f-bda7508804b8)

关于Surge的使用这里不再描述，具体请百度油管进行学习

### 2.3.1 静态路由
首先设置静态路由，先下载txt文件，然后导入。
文件：

[static_route.txt](https://github.com/user-attachments/files/15949235/static_route.txt)

图：
![截屏2024-05-27 12 33 02](https://github.com/kkkgo/PaoPaoDNS/assets/59858726/f99ea0d2-b53d-46bf-9ebe-db063fcce768)

### 2.3.1 设置dhcp
根据图片进行设置
![截屏2024-05-27 12 49 07](https://github.com/kkkgo/PaoPaoDNS/assets/59858726/ecc57b25-e09f-4098-9b82-07e212383eb9)

# 三、总结
总体上比较简单和upcg比较类似。不过不得不说Surge确实香啊。（缺点是真的贵啊）。
一共写了三个经验分享，我个人心中稳定性排名：
第一是 Surge，第二是SingBox，第三是 PaoPaoGateWay
