### DISCUSSION TITLE
想咨询下，如何实现SOA TXT MX类型记录解析

### DISCUSSION THREAD

**Discussion by xiaoyawl** [kkkgo/PaoPaoDNS#165] [问答和帮助]
因为有需求想实现SOA NS A AAAA TXT MX类型的解析

**Comment by kkkgo** [comment]
A/AAAA记录可以使用RULES_TTL功能或者USE_HOSTS功能实现。
添加除了A/AAAA记录以外类型的本地记录解析，可以通过编辑`unbound_custom.conf`实现，具体语法可以参考unbound官方文档，例如添加微软KMS服务器SRV记录
打开`/data/unbound_custom.conf`编辑：
```yaml
#Example of setting up SRV records for KMS server VLMCS.
#假设你的内网后缀是.lan，KMS服务器地址是192.168.1.2或者kms.ad.local

server:
    local-zone: "_vlmcs._tcp.lan." static
    local-data: "_vlmcs._tcp.lan. IN SRV 0 0 1688 kms.ad.local."
    local-data: "_vlmcs._tcp.lan. IN SRV 0 0 1688 192.168.1.2."
```
