### DISCUSSION TITLE
请教一下PaoPaoDNS内的mosdns配置

### DISCUSSION THREAD

**Discussion by xxllllll** [kkkgo/PaoPaoDNS#17] [问答和帮助] [answered]
大佬好，我想把将所有域名解析的 Cloudflare IP 重定向至最快 IP，

`- matches: resp_ip &/data/cf_ips
        exec: black_hole 127.0.0.1 # 自行修改为最优 IP
` 
我试着把这段代码放进默认的mosdns.yaml中去，但是不生效，请教一下应该如何使其生效。感谢！

**Comment by kkkgo** [comment]
贴出你修改后的完整yaml配置文件

**Comment by xxllllll** [comment]
```
log:
    file: ""
    level: error

plugins:
  - tag: "force_cn_list"
    type: "domain_set"
    args:
      files:
        - "/data/force_cn_list.txt"
  - tag: local_unbound
    type: forward
    args:
      upstreams:
        - addr: "udp://127.0.0.1:5301"
  - tag: cnip
    type: mmdb
    args:
      file: "/data/Country-only-cn-private.mmdb"

  - tag: main_sequence
    type: sequence
    args:
        - matches: qtype 65
          exec: reject 0
        - matches: 
          - qtype 28
          exec: reject 0
        - matches: 
          - "!qtype 1 2 5 28 15 16 33 6 99"
          exec: $local_unbound
        - matches: has_wanted_ans
          exec: accept
        - matches: qname $force_cn_list
          exec: $local_unbound
        - matches: qname $force_cn_list
          exec: accept
        - matches: 
          - "!qtype 1 28"
          - has_wanted_ans
          exec: accept
        - matches: resp_ip_mmdb $cnip CN
          exec: accept
        - matches: resp_ip &/data/cf_ips
          exec: black_hole 127.0.0.1
        - exec: drop_resp
        - exec: reject 0
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53
  - tag: "tcp_server"
    type: "tcp_server"
    args:
      entry: main_sequence
      listen: :53
      idle_timeout: 5
```
