### DISCUSSION TITLE
X86 Ros 使用 docker 创建PaopaoDns-ADhome-Mihomo-yacd 使用记录

### DISCUSSION THREAD

**Discussion by gukey** [kkkgo/PaoPaoDNS#185] [经验分享]
# X86 Ros 使用 docker 创建PaopaoDns-ADhome-Mihomo-yacd 使用记录

![pdf文件](http://forumupload.ru/uploads/001b/b0/1b/8/893477.jpg)
[PDF 教程下载地址](https://pan.w10.xyz/index.php?share/file&user=102&sid=2Ct4zYuN)

![windows](http://forumupload.ru/uploads/001b/b0/1b/8/893477.jpg)
[Server 2019/windows11/10-Hyper-V虚拟机专用精简版优化版系统](https://www.right.com.cn/forum/thread-8297905-1-1.html)

**前言，使用 paopaodns 搭配泡泡网关使用了很长时间，软路由基本一只欧式4个虚拟机，Ros，dns，adhome（过滤广告），paopao网关，4个使用下来，内存差不多在设置在4个G多，cpu 每个虚拟机2个核心，软路由整体负载还是有些高的，因为本身是Windows Server 2019 hyper-V虚拟机，还有流出一部分性能来跑 jellyfin，迅雷，ftp 照片通不等服务，阴差阳错，没事查找 ros 破解版，无意中找到了最新的 X86 ros 安装镜像，直接直通网卡到虚拟机，效果显著，可以跑满宽带网速，测试了下自带的 Ros 自带的 docker 服务，也能使用，就萌生了本次折腾的念头，看看效果图；**
![hyper](http://forumupload.ru/uploads/001b/b0/1b/8/441310.png)
![run](http://forumupload.ru/uploads/001b/b0/1b/8/963600.png)

**1G内存，同时跑3个 docker+拨号，DHCP服务这些，还剩300MB多内存，然后使用电视的 smartTV 看油管视频，速度也不错，个人非常满意，即节省了硬件性能，也能满足自己的需求；**

简单说说 hyper-V 虚拟机网卡直通，对网络的提升效果非常显著，可以跑满千兆带宽，虚拟网卡只能有一半不到的洗能，损失严重，推荐能上直通一定优先考虑直通，加上 Ros 的网卡驱动简直不要太完美，直接就能用，非常方便：

**1、首先创建好自己的虚拟机，然后打开直通软件:**

[直通工具-下载](https://pan.w10.xyz/index.php?share/file&user=102&sid=jx5BAFY2)

2、点击要直通网卡的虚拟机，点下面3个小点，搜net，就会弹出本机所有的网络设备，选择要直通的网卡，点“**如此甚好**”就添加成功了；

![net](http://forumupload.ru/uploads/001b/b0/1b/8/930788.png)

### X86 Ros 虚拟机安装

Ros 破解版下载地址（无视硬盘SN，随意安装激活）：[MikroTikPatch](https://github.com/elseif/MikroTikPatch)

下载地址：国内镜像下载 密码: elseif

[ [123pan](https://www.123pan.com/s/IpxgTd-BYjQh.html) ] [ [7.15.3](https://elseif.lanzouj.com/b00cre7g7a)] [ [7.15.3-arm64](https://elseif.lanzouj.com/b00cre7g8b) ] [ [6.49.15](https://elseif.lanzouj.com/b00crdq4ji) ] [ [6.49.13](https://elseif.lanzouj.com/b00crdq4kj) ]

[winbox 下载](https://pan.w10.xyz/index.php?share/file&user=102&sid=SDM5WtsI)

下载对应X86版本的ISO文件，虚拟机加载镜像，选择 “a” （全部），然后按 “i” 键进行安装，重启虚拟机，用winbox 配置；

支持:在线更新、在线授权、云备份、DDNS

![1](http://forumupload.ru/uploads/001b/b0/1b/8/108301.png)

![2](http://forumupload.ru/uploads/001b/b0/1b/8/16072.png)

### x86模式授权许可

![3](http://forumupload.ru/uploads/001b/b0/1b/8/16072.png)

### x86模式在线授权(v6.x)

![4](http://forumupload.ru/uploads/001b/b0/1b/8/654884.png)

### Chr模式在线授权

![5](http://forumupload.ru/uploads/001b/b0/1b/8/108301.png)

### Chr模式授权许可

![6](http://forumupload.ru/uploads/001b/b0/1b/8/603004.png)

## 如何使用Shell

```
安装 option-{version}.npk 包
telnet到RouteRos,用户名devel（最后一位是字母L小写）,密码与winbox 登录的admin的密码相同
```

## 如何授权许可

```
进入shell
 /system/telnet 127.0.0.1  // 用户名devel（最后一位是字母L小写）,密码与winbox 登录的admin的密码相同
```

![shell](http://forumupload.ru/uploads/001b/b0/1b/8/692759.png)

```
进入后运行运行 keygen,出来密钥后exit退出，然后复制密钥，右键粘贴，出现 Reboot提示，重启即可；
参考上图。
Chr镜像支持在线授权许可
```

## 如何使用Python

```
安装 python3-{version}.npk 包
telnet到RouteRos,用户名devel,密码与admin的密码相同
运行 python -V
```

### npk.py

```
对npk文件进行解包，修改，创建，签名和验证
```

### patch.py

```
替换公钥并签名
```

### RouteRos docker使用教程

# 启用

默认是关闭容器功能的，我们要开启

```
/system/device-mode/update container=yes
```

![docker](http://forumupload.ru/uploads/001b/b0/1b/8/312220.png)

在5分钟内断电重启一下

重启完成输入，可以看到容器功能已经打开 **yes**;

```
/system/device-mode> /system/device-mode/print
```

![docker2](http://forumupload.ru/uploads/001b/b0/1b/8/845113.png)

#### 1、添加基础设置

为每个容器都是要创建 **veth** 接口，如本教程有3 个 docker 容器，就创建 3 个虚拟网卡，然后添加到 docker **桥接** 接口上；

![1](http://forumupload.ru/uploads/001b/b0/1b/8/446149.png)

* **Ros** 中新建虚拟网卡，配置IP，并将网卡添加到桥接接口里面，实现局域网内主机访问；
* **Ros-container**-中设置paopaodns 的环境变量，此处需要注意的是，**需要将所有变量的名称设置为同一个**，方便后面创建 docker 容器的时候调运；
* **Ros-files**中创建一个目录，在container-中设置挂载路径，具体如图所示；

#### 2、创建镜像

此处需要说明，进行下列操作前，先安装**作者** 默认 paopaoGateWay生成一个iso，将Ros 的dns设置为paopaodns 的ip地址，就可以分流了，然后虚拟网卡配置的地址和当前地址不重复即刻，等拉取完下面的镜像，就可以将主机上的paopaodns 和网关的地址设置在 Ros 的容器对应的网卡上，效果和单独搭建虚拟机一样；

![config](http://forumupload.ru/uploads/001b/b0/1b/8/534260.jpg)

首先需要设置仓库地址 ：https://registry-1.docker.io
![veth](http://forumupload.ru/uploads/001b/b0/1b/8/433975.jpg)
![env](http://forumupload.ru/uploads/001b/b0/1b/8/966772.jpg)

![mou](http://forumupload.ru/uploads/001b/b0/1b/8/47738.jpg)

* paopaodns 容器创建，直接在Ros命令行执行，`mounts=dns  envlist=dns` 为之前配置的环境变量，下面命令执行效果为拉取云端docker 镜像，启用日志和开机自启动，设置镜像备注；

  ```sh
   /container/add remote-image=sliamb/paopaodns:latest interface=veth1 root-dir=docker/paopaodns logging=yes mounts=dns  envlist=dns start-on-boot=yes comment=paopaodns
  
  
  ```

* adhome

  ```sh
   /container/add remote-image=adguard/adguardhome interface=veth2 root-dir=docker/adhome logging=yes start-on-boot=yes comment=adhome
  ```

* mihomo-yacd

  ```sh
   /container/add remote-image=yilee01/mihomo-yacd interface=veth3 root-dir=docker/clash logging=yes start-on-boot=yes  comment=Clash
  ```

启用3个 docker 镜像，adhome 直接进入3000端口配置，上游设置为paopaodns 的IP即刻，不需要启用缓存，paopaodns 会讲配置文件挂载到Ros的 mydata目录上，可以直接用ssh连接Ros 编辑文件；

mihomo-yacd 需要上传配置文件，我自己的目录在Ros-Files-docer/clash目录下；

下载 修改的配置文件,默认使用 **paopaodns** 解析：

[Clash-config_下载地址](https://pan.w10.xyz/index.php?share/file&user=102&sid=hk7MetB2)     

```yaml
mixed-port: 7890
allow-lan: true
log-level: info
mode: global
external-controller: 0.0.0.0:9090
ipv6: false
profile:
  store-fake-ip: true
  store-selected: true
hosts:
    paopaogateway.dns: 127.0.0.1
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 7.0.0.0/8
  nameserver:
    - 192.168.1.5

  
proxies:
  - name: "x-ui-081"
    type: vless
    server: 239.28.10.151
    port: 54514
    uuid: 118175a2-44f6-43ac-981f-44c6940e3f50
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.yahoo.com # REALITY servername
    reality-opts:
      public-key: tP-FA11CT9jTek4GLcnCjkNZA3iZmMKU-lo9w94-Dgg
      short-id: c753041e # optional
    client-fingerprint: chrome # cannot be empty

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
```

 **ssh连接到Ros，密码为winbox登录账号密码：**

![clash](http://forumupload.ru/uploads/001b/b0/1b/8/469134.jpg)

上传到当前目录，直接覆盖，然后 访问  **mihome IP地址:8080**端口，访问后台，重载配置和核心即刻正常使用，需要说明的是，默认的 **fake-ip** 地址段还是 **7.0.0.0/8** 地址段，需要将这个地址段添加静态路由，paopaodns 按照作者给出的配置即可，

![yacd](http://forumupload.ru/uploads/001b/b0/1b/8/440298.jpg)
![yacd1](http://forumupload.ru/uploads/001b/b0/1b/8/755607.jpg)

**Comment by kkkgo** [comment]
docker镜像可以用public.ecr.aws，国内能直连。
详情看更新日志。

**Comment by falltree** [comment]
多谢分享，有些细节的地方还没有搞清楚。
请问paopaodns，adguard，clash三者之间的关系和ip是怎么分配的？
paopaodns里custom forward的192.168.1.3，这个是clash吗？
clash配置里面的nameserver 192.168.1.5这个又是哪个？adguard？还是paopaodns？
我的理解是ROS的dns设置成paopaodns，paopao又forward给clash，clash分配fakeip 7.0.0.x，ROS里路由设置7.0.0.x走clash，非fakeip走直连，那么adguard起了什么作用呢？貌似没有需要经过adguard的流量。

还有clash配置里的
hosts:
    paopaogateway.dns: 127.0.0.1
这个paopaogateway.dns是什么作用，这里不是没有paopaogateway吗？

另外建议前面介绍安装虚拟机，ros授权，打开容器部分可以删除，占了大量篇幅，实际和主题无关。

**Reply by gukey** [reply]
> 多谢分享，有些细节的地方还没有搞清楚。 请问paopaodns，adguard，clash三者之间的关系和ip是怎么分配的？ paopaodns里custom forward的192.168.1.3，这个是clash吗？ clash配置里面的nameserver 192.168.1.5这个又是哪个？adguard？还是paopaodns？ 我的理解是ROS的dns设置成paopaodns，paopao又forward给clash，clash分配fakeip 7.0.0.x，ROS里路由设置7.0.0.x走clash，非fakeip走直连，那么adguard起了什么作用呢？貌似没有需要经过adguard的流量。
> 
> 还有clash配置里的 hosts: paopaogateway.dns: 127.0.0.1 这个paopaogateway.dns是什么作用，这里不是没有paopaogateway吗？
> 
> 另外建议前面介绍安装虚拟机，ros授权，打开容器部分可以删除，占了大量篇幅，实际和主题无关。

192.168.1.5是adhome 的IP， 上游配置是paopaoDNS 192.168.1.6的IP，用来记录访问日志，去广告用的，192.168.1.3就是clash网关，配置文件直接用这个就可以，修改下节点信息，其他无需修改，上传就能用,去除了不必要配置，另外上面的ROS授权实际上是做个记录，毕竟是破解的项目，说不定那天就没了，方便以后的人查看：
```
mixed-port: 7890
allow-lan: true
log-level: info
mode: global
external-controller: 0.0.0.0:9090
# secret: '123456'
ipv6: false


profile:
  store-fake-ip: true
  store-selected: true
  
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 7.0.0.0/8
  fake-ip-filter:
    - '*.taobao.com'
    - '*.jd.com'

proxies:
  - name: "x-ui-08"
    type: vless
    server: 154.18.21.131
    port: 22514
    uuid: e68175a2-23f6-43ac-981f-456940e3f50
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.yahoo.com # REALITY servername
    reality-opts:
      public-key: tP-FAmQCT6jTek4GLcnCjkNZA3iZmMKU-lo9w94-Dgg
      short-id: c75c345e # optional
    client-fingerprint: chrome # cannot be empty


tun:
  enable: true
  stack: system 
#  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53

```
