### DISCUSSION TITLE
【更新日志】2024/08/14 PaoPaoDNS 优化加载速度、新增custom_cn_mark.txt、RULES_TTL新增通配匹配、更高级自定义的custom_mod功能

### DISCUSSION THREAD

**Discussion by kkkgo** [kkkgo/PaoPaoDNS#187] [更新日志]
- 增加内嵌的数据处理、大幅优化容器启动时加载配置和数据的速度、优化部分参数计算。
- 添加了部分环境变量防呆处理。
- `USE_MARK_DATA`功能已经趋于稳定，***从该版本开始将默认值设定为`yes`***。

  
 ***Tips: 新增aws镜像（自2024/06/11）***
如果你的网络环境访问Docker Hub镜像有困难，***可以尝试使用public.ecr.aws镜像:***    
- 示例： `docker pull public.ecr.aws/sliamb/paopaodns`  
- 示例： `docker run -d --name paopaodns public.ecr.aws/sliamb/paopaodns`

# 新增custom_cn_mark.txt
在`USE_MARK_DATA`功能设置为`yes`的情况下，可以在`/data/custom_cn_mark.txt`中额外定义标记为`CN`的域名。填写格式与其他 `force_*_list.txt`一致。参考 https://github.com/kkkgo/PaoPaoDNS/discussions/122 
有限的使用场景：当域名被`USE_MARK_DATA`或者被IP库认定为非`CN`域名但你希望把他当成`CN`域名处理的时候。
**`custom_cn_mark.txt`与`force_recurse_list.txt`的区别**：
- 匹配优先级与`USE_MARK_DATA`一致位于匹配末尾，参考 https://github.com/kkkgo/PaoPaoDNS/discussions/122
- 位于`force_recurse_list.txt`的域名不会进行`CNFALL`处理，强制进行递归，解析失败不会回退转发。
- 仅在`USE_MARK_DATA`功能设置为`yes`的情况下生效。
-  实际适用场景: 域名是anycast地址，境内解析可信任， 子域名包含CDN，不方便直接全部加入`force_dnscrypt_list.txt`的情况。
# RULES_TTL新增通配匹配
```yaml
# 重定向www.qq.com
www.qq.com@@1.2.3.4
www.qq.com@@5.6.7.8 #可以指定多项记录
www.qq.com@@2404:6800:4008:c06::99

# CNAME www.qq.com 到qq.03k.org
www.qq.com@@qq.03k.org

# 注意，使用@@默认为子域名匹配，上述示例会匹配*.www.qq.com和www.qq.com

# 使用通配符匹配（同样适用于CNAME）：
k8s.*.qq.com@@1.2.3.4 # k8s.xxx.qq.com和k8s.aaa.xxx.qq.com都会被匹配
dl[0-8].qq.com@@1.2.3.4 # dl8.qq.com会被匹配，dl9.qq.com不会被匹配，dl88.qq.com不会被匹配
ftp[a-c].qq.com@@1.2.3.4 # ftpc.qq.com会被匹配，ftpd.qq.com不会被匹配
dl[0-8][2-4][x-z].qq.com@@1.2.3.4 # dl84z.qq.com会被匹配，dl11x.qq.com不会被匹配，dl23t.qq.com不会被匹配
```

*注意，这`不是`正则匹配，仅允许使用以下字符：
- 字母 `a-z`
- 数字 `0-9`
- 连字符 `-` 、下划线`_`
- 通配符 `*`, 可以匹配任意长度的任意字符
- 小数点`.` 仅作为实际字符使用，无特殊匹配含义
- 方括号`[]` 用于匹配方括号内的任意一个字符
- Tips: 非英文域名请先进行Punycode编码转换

# 更高级自定义的custom_mod功能
`custom_mod`功能进行了重构优化，可以智能合并处理流程。  
`custom_mod`的Zones的zone可以一次性写入多个域名，也可以使用list的规则写法，也可以直接引用外部文件（必须以反斜杠`/`的绝对路径开头），以空格隔开，例如：
```yaml
Zones:
 - zone: a.com domain:b.com full:c.com regexp:dl[0-9]+\.qq\.com$ keyword:google /data/mylist.txt
   dns: udp://10.10.10.3:53,udp://10.10.10.4:53
   ttl: 0
   seq: top
   socks5: no
```
`custom_mod`的Swaps的env_key可以对应多个cidr_file，一个cidr_file仅可以匹配一个env_key。例如：
```yaml
Swaps:
 - env_key: test_ip
   cidr_file: "/data/test_cidr.txt"
 - env_key: test_ip
   cidr_file: "/data/test_cidr2.txt"
 - env_key: test_ip
   cidr_file: "/data/test_cidr3.txt /data/test_cidr4.txt"
```
会被合并为匹配到`/data/test_cidr.txt /data/test_cidr2.txt /data/test_cidr3.txt /data/test_cidr4.txt`均重写为`test_ip`。
```yaml
Swaps:
 - env_key: test_ip
   cidr_file: "/data/test_cidr.txt"
 - env_key: test_ip2
   cidr_file: "/data/test_cidr.txt"
```
由于`/data/test_cidr.txt`已经被`test_ip`匹配过，`test_ip2`的规则将会被跳过。

新增`Hosts`模块，可以自定义域名的解析直接映射为指定变量的结果。域名写法与Zones模块一样，支持引入外部文件。  
`Hosts`模块将位于最高匹配优先级。
```yaml
Hosts:
 - env_key: test_ip
   zone: a.com domain:b.com full:c.com regexp:dl[0-9]+\.qq\.com$ keyword:google /data/mylist.txt
```

Tips :
-  `env_key`配合`custom_env.ini`使用可以实现变量改变的时候重新加载。
- `custom_mod`功能引入的外部文件仅在容器启动的时候加载，如果不存在会跳过规则。`custom_mod`引入的外部文件不会被额外监测，发生变化的时候不会重新加载。如果需要重新加载所有外部文件，可以使用`reload.sh`命令，示例：`docker exec paopaodns reload.sh`

**Comment by Mxzjxs** [comment]
我已经部署好了，我要怎么更新，可以完整保存以前的所有数据和设置。重新拉取镜像 然后关闭旧容器  打开新容器，以前的设置不就没有了吗

**Reply by kkkgo** [reply]
看文档。容器版本更新不会覆盖该文件。

**Comment by taoersvip** [comment]
paopao您好，请问dns查询后可否增加一个回调功能，或者一个推送功能？主要想通过解析结果里面的标记，走特定路由

**Comment by a18ccms** [comment]
k8s.*.qq.com@@1.2.3.4 # k8s.xxx.qq.com和k8s.aaa.xxx.xxx.com都会被匹配
这里不是很理解？为什么k8s.*.qq.com会匹配k8s.aaa.xxx.xxx.com？？ 里面的qq被舍弃了？

**Reply by lixuy** [reply]
文档打错了

**Reply by a18ccms** [reply]
> 文档打错了

这个的匹配机制，我有些疑问，谁能帮忙解惑。文档说.作为实际符号有意义。那  .xxx.com 不应该匹配a.xxx.com b.xxx.com 为什么还匹配xxx.com 而我设置*.xxx.com也是这个现象。实际情况为xx.h.xx.com 为我定义的内网地址192.168.1.2 h.xx.com为公网地址 我设置上面两种*.h.xx.com和.h.xx.com都会改变h.xx.com的ip为1.2。很迷惑这个匹配机制，到底该怎么写能把h.xx.com排除。所以我现在只能把h.xx.com改为hx.xx.com以避免匹配上。

**Reply by kkkgo** [reply]
mosdns的匹配方法会将 .xxx.com 规范化（去除前缀点号，转换为xxx.com），然后按标签 ["com", "xxx"] 存储到树中，因此会包含xxx.com本身。
需要更高级正则匹配可以使用`custom_mod`功能的`hosts`模块。
```yaml
Hosts:
 - env_key: ddns_ip
   zone: regexp:[0-9a-z]+\.xxx\.com$
```

**Reply by a18ccms** [reply]
> mosdns的匹配方法会将 .xxx.com 规范化（去除前缀点号，转换为xxx.com），然后按标签 ["com", "xxx"] 存储到树中，因此会包含xxx.com本身。 需要更高级正则匹配可以使用`custom_mod`功能的`hosts`模块。
> 
> ```yaml
> Hosts:
>  - env_key: ddns_ip
>    zone: regexp:[0-9a-z]+\.xxx\.com$
> ```

原来是这样，明白为什么了。还有活捉作者了，趁机感谢大神这么优秀的作品，真的好用。看到回复后，就开始从ttl转到custom_mod.也汇报一下转换的过程和碰到的问题。添加环境变量之后添加hosts段，yaml里面的正则要用双斜杠。之后使用reload进行重载，无错误就可以。此方法完美解决之前疑问的问题。
```
Hosts:
  - env_key: work_ip
    zone: regexp:[0-9a-z]+\\.w\\.xxx\\.com$
docker exec paopaodns reload.sh
```
