### DISCUSSION TITLE
启动的时候报 Error reading config file: While parsing config: yaml: line 20: did not find expected key 错误

### DISCUSSION THREAD

**Discussion by biggbuddy** [kkkgo/PaoPaoDNS#194] [问答和帮助] [answered]
启动的时候报如下错误， 不影响使用， test.sh也是全部通过的。
```
paopaodns  | dat size pass.
paopaodns  | global_mark hash: OK.
paopaodns  | /data
paopaodns  | Cloaking rule .mydomain.com 10.0.0.104
paopaodns  | Valid1 domain: .mydomain.com
paopaodns  | Error reading config file: While parsing config: yaml: line 20: did not find expected key
paopaodns  | 2024-08-28T22:53:09.651+0800       INFO    working directory changed       {"path": "/tmp"}
paopaodns  | 2024-08-28T22:53:09.654+0800       INFO    main config loaded      {"file": "/tmp/mosdns.yaml"}
paopaodns  | PID   USER     TIME  COMMAND
paopaodns  |     1 root      0:00 {init.sh} /bin/sh /usr/sbin/init.sh
```
看不出来是在读哪个文件的时候报的错，但看了下data目录下的所有*.yaml文件， 20行貌似都没有看到错误。

**Comment by kkkgo** [comment, marked as answer]
你是不是自定义custom_mod.yaml

**Reply by biggbuddy** [reply]
是的， 错误地把下面应该放在 unbound_custom.conf  的内容放在了 custom_mod.yaml 中， 修改后就好了
```
#Example of setting up SRV records for KMS server VLMCS.
#Assuming your local network suffix is .lan.
# 原文本是所有内容都注释掉
server:
    local-zone: "_vlmcs._tcp.lan." static
    local-data: "_vlmcs._tcp.lan. IN SRV 0 0 1688 kms.ad.local."
    local-data: "_vlmcs._tcp.lan. IN SRV 0 0 1688 10.0.0.1."
```
