### DISCUSSION TITLE
请问支持根据gfw列表进行分流吗？

### DISCUSSION THREAD

**Discussion by ooroot** [kkkgo/PaoPaoDNS#214] [问答和帮助]
首先非常感谢大佬无私奉献
尝试过很多方案，还是大佬的方案最完美，同样节点速度都是第一梯队的。
只是目前购买的是小流量机场，目前根据国内国外分流，有些不需要走代理的国外网站也走代理出口，流量很快用完了。
不知道能不能改成根据gfw列表或者自定义列表进行分流。
翻了很多Issues，没发现有讨论的，故而提问，望不吝解惑，谢谢

**Comment by TOPGUUN** [comment]
把AUTO_FORWARD设置成no.
把 https://github.com/pmkol/easymosdns/blob/rules/gfw_domain_list.txt 里的域名手动添加到 force_forward_list.txt 
批量在每个域名前批量添加domain:

**Reply by ooroot** [reply]
谢谢你，这个思路感觉是可行的，只是不能自动更新列表，有没有优雅一点的做法
类似clash mihomo
google_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"
  
rules:
  - RULE-SET,google_domain,proxy

**Reply by TOPGUUN** [reply]
那你用这个试试https://github.com/Loyalsoldier/clash-rules
用最下面黑名单模式 Rules 配置方式

**Reply by ooroot** [reply]
你的意思是
docker配置ppgw
AUTO_FORWARD设置成no
然后用
ppgw.ini
```
#paopao-gateway

# mode=socks5|ovpn|yaml|suburl|free
# default: free
mode=yaml

# Set fakeip's CIDR here
# default: fake_cidr=7.0.0.0/8
fake_cidr=7.0.0.0/8

# Set your trusted DNS here
# default: dns_ip=1.0.0.1
dns_ip=192.168.123.7
# default: dns_port=53
# If used with PaoPaoDNS, you can set the 5304 port
dns_port=5304

# Clash's web dashboard
clash_web_port="80"
clash_web_password="******"

# default：openport=no
# socks+http mixed 1080
openport=no

# default: udp_enable=no
udp_enable=no

# default:30
sleeptime=30

# socks5 mode settting
# default: socks5_ip=gatewayIP
socks5_ip="192.168.123.9"
# default: socks5_port="7890"
socks5_port="7890"

# ovpn mode settting
# The ovpn file in the same directory as the ppgw.ini.
# default: ovpnfile=custom.ovpn
ovpnfile="custom.ovpn"
ovpn_username=""
ovpn_password=""

# yaml mode settting
# The yaml file in the same directory as the ppgw.ini.
# default: yamlfile=custom.yaml
yamlfile="custom.yaml"

# suburl mode settting
suburl="https://xxx/api/v1/client/subscribe?token=69b12d57863da83675896e4beb9fd"
subtime=1d

# fast_node=check/yes/no
fast_node=no
test_node_url="https://www.youtube.com/generate_204"
ext_node="Traffic|Expire| GB|Days|Date"
cpudelay="3000"
fall_direct="no"
# dns burn setting
# depend on fast_node=yes & mode=suburl/yaml
dns_burn=no
# If used with PaoPaoDNS, you can set the PaoPaoDNS:53
ex_dns="192.168.123.7:53"

# Network traffic records
net_rec=yes
max_rec=5000
```
然后手搓custom.yaml规则出站

**Reply by ooroot** [reply]
试过yaml模式，搓custom.yaml规则，因为sleeptime=30，机场订阅更新时间不能单独设置，目前只能选择是用suburl模式

**Reply by TOPGUUN** [reply]
我没用PAOPAO GATEWAY,只用的PAOPAO DNS后面接OPENCLASH.所以对你的情况我也不知道怎么改,不过我说的第一种方法应该可行

**Comment by kkkgo** [comment]
1. 流量用的快的话ppgw有流量记录功能，你可以把用量比较大但又不需要的域名加到force_dnscrypt_list.txt .
2. AUTO_FORWARD为no的情况下，force_forward_list.txt复制decode后的gfwlist进去就可以：   https://github.com/Loyalsoldier/v2ray-rules-dat/raw/refs/heads/release/gfw.txt
（域名没有指定的话缺省规则就是domain:）
3. gfwlist实际上大部分域名以及更新的域名都是访问频率比较低甚至已经消失的网站，基本上复制一次也就满足常用网站规则，个别需求的网站都可以自己添加，全依赖list不如无list，合适自己的就行；如果你确实希望自动更新，也有很多项目比如https://github.com/cokebar/gfwlist2dnsmasq 
4. custom_mod功能可以指定多个文本列表转发到指定dns服务器，所以你只要实现把文件下载下来就行，方法很多，不详述，或者再简单点你git pull都行。如果需要重新加载所有外部文件，可以使用reload.sh命令，示例：`docker exec paopaodns reload.sh`
5. 很显然你需要自己实现文件的校验，因为源头文件可能并没有提供sha文件这种东西，换句话说，当网络错误比如返回了一个错误页的时候，也会导致你的txt抓出来的是错误页，这可能导致一连串的错误，或者下载到一半出错了，列表只下了一半，这都是你需要考虑的问题，这是暂时没有做这个功能的原因，也是第三点建议的原因，复制一次就够用。
6. 搓custom.yaml规则的话，clash是有proxy-provider这个东西的，可以自己定义订阅更新时间，更多功能的选择是建议subconverter

**Reply by ooroot** [reply]
感谢大佬解惑，我稍后会尝试你建议的第1、2点，估计gfw列表也不用频繁更新。
之前的试过手搓了一个custom.yaml，使用了几天，感觉问题不大，大概是国外流量再筛选了一次分流
```
proxy-providers:
    provider1:
        type: http
        url: "机场地址"
        interval: 172800
        path: ./provider1.yaml
        health-check:
            enable: true
            url: http://www.gstatic.com/generate_204
            interval: 300

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Manual-Select
      - Auto-Select
      - DIRECT
  - name: Manual-Select
    type: select
    use:
      - provider1
  - name: Auto-Select
    type: url-test
    tolerance: 10
    use:
      - provider1

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
    
rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,telegramcidr,PROXY
  - MATCH,DIRECT
```
