### DISCUSSION TITLE
请问作者大大和各位大佬，如何国内部分也使用DOH？

### DISCUSSION THREAD

**Discussion by WhiteByeBye** [kkkgo/PaoPaoDNS#223] [问答和帮助] [answered]
可能问题不太准确，就是我们是校园网，一到固定时间，会屏蔽对一些网页的访问，比如淘宝，抖音，今日头条，众多国产游戏等。好像是通过dns污染实现的？修改本地dns为公共dns也不行，只有使用doh才可以（dot也不行），貌似目前的paopaodns国内部分查询是普通的dns（ip地址）？

我之前是在软路由上使用mosdns，然后国内的dns只使用doh（比如阿里的doh）。但是总是莫名其妙断流，所以想自建dns，昨天部署好paopaodns后一切都很顺畅，但是到点屏蔽网站这个还是出现了。就是想问问作者大大和各位大佬怎么办，是不是国内部分的也用doh就好了？但是我没找到在哪里修改

**Comment by kkkgo** [comment]
https://github.com/kkkgo/PaoPaoDNS/discussions/131

**Comment by TOPGUUN** [comment, marked as answer]
大佬的外接没法直接用DOH,你还是要再建个MOSDNS做DOH服务器
```
server:
    forward-zone:
        name: "."
        forward-addr: 127.0.0.1@5335
```

MOSDNS不要做分流,只添加DOH服务器.用的V4版本比如这样:

```
log:
    file: "./mosdns.log"
    level: error

plugins:
  - tag: cache
    type: cache
    args:
      size: 5000
      compress_resp: true
      lazy_cache_ttl: 86400
      cache_everything: true
      lazy_cache_reply_ttl: 3

  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: "https://223.5.5.5/dns-query"
        - enable_http3: true
        - addr: "https://1.12.12.12/dns-query"

  - tag: forward_apad_pro
    type: fast_forward
    args:
      upstream:
        - addr: "https://doh.apad.pro/dns-query"
          bootstrap: "119.29.29.29"

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - cache
        - primary:
            - forward_local
          secondary:
            - forward_apad_pro
          fast_fallback: 150
          always_standby: false

servers:
  - exec: main_sequence
    timeout: 5
    listeners:
      - protocol: udp
        addr: "0.0.0.0:5335"
      - protocol: tcp
        addr: "0.0.0.0:5335"
```
