### DISCUSSION TITLE
如果unbound递归转发不是dnscrypt，而是转发给自建mosdns的可行吗？

### DISCUSSION THREAD

**Discussion by 4thanks** [kkkgo/PaoPaoDNS#23] [想法]
自从搞dns后，偶尔有意外发现，经过一段时间使用比对后，感觉mosdns自定义多组dns比dnscrypt好用些（可能不够严谨）。

比如Instagram app，之前偶然在手机使用apad.pro的doh dns，在电信和联通网络测试过是可以正常使用的，虽然偶尔不稳定，但够用。
后来在路由也从smartdns换到mosdns，把 [已知的 DNS 提供商](https://adguard-dns.io/kb/zh-CN/general/dns-providers)加入自定义多组dns，类似下面的配置，国内国外fallback，基本能够满足我偶尔访问连接一些不太稳定的国外网站。

在使用paopaodns后那些“边缘不稳定”的国外网站又不能“正常”访问连接了，所以想着paopaodns是不是可以逆向递归mosdns呢？感觉比较小众需求，不知道可不可行？

```yaml

  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '1.12.12.12:443'
        - addr: 'https://doh.pub/dns-query'
          dial_addr: '120.53.53.53:443'
        - addr: 'tls://dot.pub'
          dial_addr: '1.12.12.12:853'
        - addr: 'tls://dot.pub'
          dial_addr: '120.53.53.53:853'
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.5.5.5:443'
        - addr: 'https://dns.alidns.com/dns-query'
          dial_addr: '223.6.6.6:443'
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.5.5.5:853'
        - addr: 'tls://dns.alidns.com'
          dial_addr: '223.6.6.6:853'
        - ....
           ....

  - tag: forward_remote
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.4.4:443'
        - addr: 'https://dns.google/dns-query'
          dial_addr: '8.8.8.8:443'
        - addr: 'tls://dns.google'
          dial_addr: '8.8.4.4:853'
        - addr: 'tls://dns.google'
          dial_addr: '8.8.8.8:853'
        - addr: 'https://cloudflare-dns.com/dns-query'
          dial_addr: '1.0.0.1:443'
        - addr: 'https://cloudflare-dns.com/dns-query'
          dial_addr: '1.1.1.1:443'
        - addr: 'tls://1dot1dot1dot1.cloudflare-dns.com'
          dial_addr: '1.0.0.1:853'
        - addr: 'tls://1dot1dot1dot1.cloudflare-dns.com'
          dial_addr: '1.1.1.1:853'
        - ....
           ....

  - tag: local_ip_sequence
    type: sequence
    args:
      - exec: $cn_local
      - matches:
          - 'resp_ip $ip_set_local'
         exec: accept
      - exec: drop_resp

  - tag: remote_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - exec: accept

  - tag: "fallback"
    type: "fallback"
    args:
      primary: local_ip_sequence
      secondary: remote_sequence
      threshold: 500
      always_standby: true
```
