### DISCUSSION TITLE
mosdns 突然报错

### DISCUSSION THREAD

**Discussion by jakeslee** [kkkgo/PaoPaoDNS#245] [问答和帮助]
用着用着突然 DNS 无响应，重新启动报错如下。

在容器中手动启动 mosdns 也会报相同的错：

```shell
mosdns start -d /tmp -c /tmp/mosdns.yaml
```

尝试把配置文件拷出来，在 kkkgo/mosdns 项目中可以正常启动。

配置如下：

```yaml
log:
    file: ""
    level: error

plugins:




  - tag: "force_recurse_list"
    type: "domain_set"
    args:
      files:
        - "./force_recurse_list.txt"

  - tag: "force_dnscrypt_list"
    type: "domain_set"
    args:
      files:
        - "./force_dnscrypt_list.txt"
        - "./cn_tracker_list.txt"

  - tag: "force_ttl_rules"
    type: "domain_set"
    args:
      files:
        - "./force_ttl_rules.txt"





  - tag: cn_test
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "udp://127.0.0.1:5301"
        - addr: "udp://223.5.5.5"
        - addr: "udp://119.29.29.29"

  - tag: local_unbound
    type: forward
    args:
      allowcode: 23
      upstreams:
        - addr: "udp://127.0.0.1:5301"

  - tag: local_unbound_fall
    type: forward
    args:
      qtime: 3
      flush: 1
      upstreams:
        - addr: "udp://127.0.0.1:5301"


  - tag: forward_unbound
    type: forward
    args:
      allowcode: 23
      concurrent: 2
      upstreams:
        - addr: "udp://127.0.0.1:5304"
        - addr: "udp://127.0.0.1:5302"

  - tag: forward_dnscrypt
    type: forward
    args:
      upstreams:
        - addr: "udp://127.0.0.1:5302"

  - tag: cnip
    type: mmdb
    args:
      file: "./Country.mmdb"

  - tag: accept
    type: sequence
    args:
        - exec: ok

  - tag: not_a_aaaa
    type: sequence
    args:
        - exec: $local_unbound
        - matches: has_wanted_ans
          exec: goto accept
        - exec: drop_resp
        - exec: $forward_unbound
        - matches: has_wanted_ans
          exec: goto accept
        - exec: drop_resp


  - tag: f_force_dnscrypt_list
    type: sequence
    args:
        - exec: drop_resp
        - exec: $forward_unbound

        - matches: has_wanted_ans
          exec: goto accept
        - exec: $forward_dnscrypt
        - matches: has_wanted_ans
          exec: goto accept
        - exec: pongerr END by f_force_dnscrypt_list.

  - tag: f_local_unbound
    type: sequence
    args:
        - exec: $local_unbound
        - matches: has_wanted_ans
          exec: goto accept
        - exec: pongerr END by f_local_unbound.
        
  - tag: f_force_ttl_rules
    type: sequence
    args:
        - exec: $forward_dnscrypt
        - exec: ttl 0-10
        - exec: goto accept

  - tag: try_cn_fall
    type: sequence
    args:
        - exec: drop_resp
        - exec: $cn_test






  - tag: main_sequence
    type: sequence
    args:


        - matches: "qtype 64 65"
          exec: pong END by block qtype 64/65.


        - matches: 
          - qname $force_dnscrypt_list
          - qtype 28
          exec: pong END by IPv6=yes, force_dnscrypt_list block aaaa.



        - matches: 
          - "!qtype 1 28"
          exec: jump not_a_aaaa
        - matches: qname $force_dnscrypt_list
          exec: goto f_force_dnscrypt_list
        - matches: qname $force_recurse_list
          exec: goto f_local_unbound
 
        - matches: qname $force_ttl_rules
          exec: goto f_force_ttl_rules



        - exec: $local_unbound_fall
        - matches: "!rcode 0"
          exec: jump try_cn_fall
        - matches: resp_ip_mmdb $cnip CN
          exec: goto accept

        - matches: 
          - qtype 28
          exec: pong END by IPv6=yes, NO CN IP block aaaa.



        - exec: goto f_force_dnscrypt_list


  - tag: respond
    type: sequence
    args:
        - exec: ok
  - tag: check_cache
    type: sequence
    args:
        - exec: cache 1024000
        - matches: has_wanted_ans
          exec: goto respond
        - exec: jump main_sequence

  - tag: udp_server
    type: udp_server
    args:
      entry: check_cache
      listen: :53
  - tag: "tcp_server"
    type: "tcp_server"
    args:
      entry: check_cache
      listen: :53
      idle_timeout: 5
  - tag: "flushd_server"
    type: "flushd_server"

```

启动日志如下：

```
====ENV TEST====

mosdns kkkgo/mosdns:240822.1

56:C 15 Jan 2025 17:49:31.982 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

Waiting for Redis rdb to load...

Waiting for Redis rdb to load...

Waiting for Redis rdb to load...

Waiting for Redis rdb to load...

Redis rdb has finished loading.

Bad CUSTOM_FORWARD=IP:PORT, IP:port. Disable AUTO_FORWARD.

Apply trackerslist...

Cloaking rule dc.imoe.tech 10.0.1.230

Valid1 domain: dc.imoe.tech

ip.sb 114.114.114.114

2025-01-15T17:49:36.216+0800	INFO	working directory changed	{"path": "/tmp"}

panic: runtime error: index out of range [16] with length 512 [recovered]

	panic: runtime error: index out of range [16] with length 512

goroutine 1 [running]:

gopkg.in/yaml%2ev3.handleErr(0xc0000478e8)

	gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d

panic({0xad6420?, 0xc000136378?})

	runtime/panic.go:770 +0x132

gopkg.in/yaml%2ev3.is_z(...)

	gopkg.in/yaml.v3@v3.0.1/yamlprivateh.go:99

gopkg.in/yaml%2ev3.yaml_parser_scan_flow_scalar(0xc0001b2008, 0xc0000470c0, 0x0)

	gopkg.in/yaml.v3@v3.0.1/scannerc.go:2462 +0x2271

gopkg.in/yaml%2ev3.yaml_parser_fetch_flow_scalar(0xc0001b2008, 0x0)

	gopkg.in/yaml.v3@v3.0.1/scannerc.go:1508 +0x6f

gopkg.in/yaml%2ev3.yaml_parser_fetch_next_token(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/scannerc.go:837 +0x845

gopkg.in/yaml%2ev3.yaml_parser_fetch_more_tokens(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/scannerc.go:677 +0x18c

gopkg.in/yaml%2ev3.peek_token(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/parserc.go:69 +0x25

gopkg.in/yaml%2ev3.yaml_parser_parse_block_mapping_key(0xc0001b2008, 0xc0001b22b8, 0x0?)

	gopkg.in/yaml.v3@v3.0.1/parserc.go:847 +0x31a

gopkg.in/yaml%2ev3.yaml_parser_state_machine(0x3?, 0x45a74b?)

	gopkg.in/yaml.v3@v3.0.1/parserc.go:188 +0xe5

gopkg.in/yaml%2ev3.yaml_parser_parse(0xc0001926e0?, 0xb15090?)

	gopkg.in/yaml.v3@v3.0.1/parserc.go:129 +0x7c

gopkg.in/yaml%2ev3.(*parser).peek(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/decode.go:106 +0x2a

gopkg.in/yaml%2ev3.(*parser).mapping(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/decode.go:279 +0x125

gopkg.in/yaml%2ev3.(*parser).parse(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0xe9

gopkg.in/yaml%2ev3.(*parser).parseChild(...)

	gopkg.in/yaml.v3@v3.0.1/decode.go:197

gopkg.in/yaml%2ev3.(*parser).mapping(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/decode.go:288 +0x238

gopkg.in/yaml%2ev3.(*parser).parse(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/decode.go:155 +0xe9

gopkg.in/yaml%2ev3.(*parser).parseChild(...)

	gopkg.in/yaml.v3@v3.0.1/decode.go:197

gopkg.in/yaml%2ev3.(*parser).document(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/decode.go:206 +0x79

gopkg.in/yaml%2ev3.(*parser).parse(0xc0001b2008)

	gopkg.in/yaml.v3@v3.0.1/decode.go:159 +0xa5

gopkg.in/yaml%2ev3.unmarshal({0xc0001b0000, 0xf1c, 0x2000}, {0xa18040, 0xc000112108}, 0xd8?)

	gopkg.in/yaml.v3@v3.0.1/yaml.go:161 +0x2d9

gopkg.in/yaml%2ev3.Unmarshal(...)

	gopkg.in/yaml.v3@v3.0.1/yaml.go:89

github.com/spf13/viper/internal/encoding/yaml.Codec.Decode(...)

	github.com/spf13/viper@v1.19.0/internal/encoding/yaml/codec.go:13

github.com/spf13/viper/internal/encoding.(*DecoderRegistry).Decode(0xc0001526a0, {0x7fff608c8dc0?, 0xc000190600?}, {0xc0001b0000, 0xf1c, 0x2000}, 0xc0001905d0)

	github.com/spf13/viper@v1.19.0/internal/encoding/decoder.go:60 +0xed

github.com/spf13/viper.(*Viper).unmarshalReader(0xc000104c40, {0xc0f780?, 0xc000190600?}, 0xc0001905d0)

	github.com/spf13/viper@v1.19.0/viper.go:1800 +0x1f9

github.com/spf13/viper.(*Viper).ReadInConfig(0xc000104c40)

	github.com/spf13/viper@v1.19.0/viper.go:1653 +0x21c

github.com/IrineSistiana/mosdns/v5/coremain.loadConfig({0x7fff608c8db4, 0x10})

	github.com/IrineSistiana/mosdns/v5/coremain/run.go:128 +0xb5

github.com/IrineSistiana/mosdns/v5/coremain.NewServer(0xc000115f50)

	github.com/IrineSistiana/mosdns/v5/coremain/run.go:107 +0x1bc

github.com/IrineSistiana/mosdns/v5/coremain.init.0.func1(0xc00013a300?, {0xb1487a?, 0x4?, 0xb1487e?})

	github.com/IrineSistiana/mosdns/v5/coremain/run.go:54 +0x1b

github.com/spf13/cobra.(*Command).execute(0xc00018e308, {0xc000148740, 0x4, 0x4})

	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca

github.com/spf13/cobra.(*Command).ExecuteC(0x1042cc0)

	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff

github.com/spf13/cobra.(*Command).Execute(...)

	github.com/spf13/cobra@v1.8.1/command.go:1041

github.com/IrineSistiana/mosdns/v5/coremain.Run(...)

	github.com/IrineSistiana/mosdns/v5/coremain/run.go:91

main.main()

	github.com/IrineSistiana/mosdns/v5/main.go:67 +0x1a

PID   USER     TIME  COMMAND

    1 root      0:00 {init.sh} /bin/sh /usr/sbin/init.sh

   23 root      0:00 crond

   57 root      0:03 redis-server unixsocket:/tmp/redis.sock

  206 root      0:00 dnscrypt-proxy -config /data/dnscrypt-resolvers/dnscrypt.toml

  224 root      0:00 unbound -c /tmp/unbound_forward.conf -p

  244 root      0:00 unbound -c /tmp/unbound_raw.conf -p

  245 root      0:00 {watch_list.sh} /bin/sh /usr/sbin/watch_list.sh

  246 root      0:00 {init.sh} /bin/sh /usr/sbin/init.sh

  247 root      0:00 ps

  248 root      0:00 {watch_list.sh} /bin/sh /usr/sbin/watch_list.sh

  249 root      0:00 {watch_list.sh} /bin/sh /usr/sbin/watch_list.sh

Setting up watches.

Watches established.
```
