### DISCUSSION TITLE
询问一个IPV6问题

### DISCUSSION THREAD

**Discussion by xxllllll** [kkkgo/PaoPaoDNS#252] [问答和帮助] [answered]
docker compose配置如下：
```
services:
    paopaodns:
    image: sliamb/paopaodns:latest
    container_name: PaoPaoDNS
    restart: always
    volumes:
      - ./PaoPaoDNS:/data
    networks:
      dns:
        ipv4_address: 172.30.1.20
    environment:
      - TZ=Asia/Shanghai
      - UPDATE=weekly
      - DNS_SERVERNAME=PaoPaoDNS
      - DNSPORT=53
      - CNAUTO=yes
      - CNFALL=yes
      - CN_TRACKER=yes
      - USE_HOSTS=no
      - IPV6=raw
      - SOCKS5=172.16.1.4:6153
      - SERVER_IP=172.16.1.250
      - CUSTOM_FORWARD=198.18.0.2:53
      - AUTO_FORWARD=yes
      - AUTO_FORWARD_CHECK=yes
      - USE_MARK_DATA=yes
      - HTTP_FILE=yes
      - ADDINFO=yes
```
使用Fake IP 分流，nslookup IPV6地址时无结果，但dig AAAA ipv6又有地址，dig ipv6显示被reject，IPV6已设置为raw，按道理来说应该有地址，测试结果如下：
```
nslookup 6.ipw.cn
Server:         172.16.1.250
Address:        172.16.1.250#53

*** Can't find 6.ipw.cn: No answer

dig AAAA 6.ipw.cn @172.16.1.250

; <<>> DiG 9.18.33-1~deb12u2-Debian <<>> AAAA 6.ipw.cn @172.16.1.250
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 431
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;6.ipw.cn.                      IN      AAAA

;; ANSWER SECTION:
6.ipw.cn.               0       IN      AAAA    2400:8905::f03c:94ff:fe1c:a95e

;; ADDITIONAL SECTION:
20250311231226.840403812.addinfo.paopaodns. 1 IN TXT "Since 1ms From:nocn forward_unbound"

;; Query time: 0 msec
;; SERVER: 172.16.1.250#53(172.16.1.250) (UDP)
;; WHEN: Tue Mar 11 23:12:26 CST 2025
;; MSG SIZE  rcvd: 155

dig 6.ipw.cn @172.16.1.250

; <<>> DiG 9.18.33-1~deb12u2-Debian <<>> 6.ipw.cn @172.16.1.250
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13629
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;6.ipw.cn.                      IN      A

;; ADDITIONAL SECTION:
20250311231238.345.reject.paopaodns. 0 IN TXT   "2001ms, END by f_force_dnscrypt_list."

;; Query time: 2003 msec
;; SERVER: 172.16.1.250#53(172.16.1.250) (UDP)
;; WHEN: Tue Mar 11 23:12:38 CST 2025
;; MSG SIZE  rcvd: 122
```
请问各位佬这是为什么？

**Comment by kkkgo** [comment, marked as answer]
不知道你在用何种版本的nslookup，这里仅讨论dig的行为：
不加查询类型的时候，默认是查询A类型，该域名并没有A记录。
https://dns.google/query?name=6.ipw.cn

**Reply by xxllllll** [reply]
感谢，dig的问题我理解了，之前的docker compose没有贴全，我修改了一下配置删除了PaoPaoDNS-China中的SERVER_IP=172.16.1.250好了。想请问下现在的配置是否有重复或者优化之处，在PaoPaoDNS上面套了一层ADG，通过指定不需要代理的主机DNS为172.30.1.10，需要代理的主机DNS为172.30.1.20来进行分流。麻烦您指正。
```
services:
  paopaodns_china:
    image: sliamb/paopaodns:latest
    container_name: PaoPaoDNS-China
    restart: always
    volumes:
      - ./PaoPaoDNS-China:/data
    networks:
      dns:
        ipv4_address: 172.30.1.10
    environment:
      - TZ=Asia/Shanghai
      - UPDATE=weekly
      - DNS_SERVERNAME=PaoPaoDNS-China
      - DNSPORT=53
      - CNAUTO=yes
      - CNFALL=yes
      - CN_TRACKER=yes
      - USE_HOSTS=no
      - IPV6=raw
      #- SERVER_IP=172.16.1.250
      - USE_MARK_DATA=yes
      - HTTP_FILE=yes
      - ADDINFO=yes
    ports:
      - "7889:7889/tcp"
      - "54:53/tcp"
      - "54:53/udp"
      - "5304:5304/tcp"
      - "5304:5304/udp"

  paopaodns_global:
    image: sliamb/paopaodns:latest
    container_name: PaoPaoDNS-Global
    restart: always
    volumes:
      - ./PaoPaoDNS-Global:/data
    networks:
      dns:
        ipv4_address: 172.30.1.20
    environment:
      - TZ=Asia/Shanghai
      - UPDATE=weekly
      - DNS_SERVERNAME=PaoPaoDNS-Global
      - DNSPORT=53
      - CNAUTO=yes
      - CNFALL=yes
      - CN_TRACKER=yes
      - USE_HOSTS=no
      - IPV6=raw
      - SOCKS5=172.16.1.4:6153
      - SERVER_IP=172.16.1.250
      - CUSTOM_FORWARD=198.18.0.2:53
      - AUTO_FORWARD=yes
      - AUTO_FORWARD_CHECK=yes
      - USE_MARK_DATA=yes
      - HTTP_FILE=yes
      - ADDINFO=yes
    ports:
      - "7890:7889/tcp"

networks:
  dns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.1.0/24
          gateway: 172.30.1.1
```
