### DISCUSSION TITLE
【更新日志】2023/07/03 PaoPaoDNS重大更新！USE_MARK_DATA和RULES_TTL功能

### DISCUSSION THREAD

**Discussion by kkkgo** [kkkgo/PaoPaoDNS#28] [更新日志]
本次更新新增两项新功能：`USE_MARK_DATA`和`RULES_TTL`
## USE_MARK_DATA：
该项默认值为no，当设置为yes的时候，将会自动更新下载预先标记处理的全球百万域名库，在判断大陆分流的时候优先使用该数据，该功能仅标记数据，后续如何处理取决你的设置（比如默认分流或者自动转发）。域名数据库来源于`paopao-pref`项目定期更新。该功能：  
  - 优点：可以优化DNS泄漏问题、提供更快速精准高效的分流
  - 缺点：会占用更多内存，增加容器启动时间
 
为什么会产生DNS泄漏（DNS Leak）：
在处理大陆分流的时候，需要先使用大陆IP递归或者大陆DNS转发请求查询域名，若解析IP在境内则接受，否则标记为境外域名。这个过程不可避免地使用了境内IP查询域名，而如果查询顺序相反，具备全球CDN的境内域名则会得到不合适的解析结果。因此经过分析筛选合并，使用服务器跑数据得到的预先标记的全球TOP百万域名库，在判断流程上提前标记，可以大大减少DNS泄漏的概率，避免境外域名查询日志被记录，同时隐藏你的真实地理位置。   
开启该功能后，你可以使用一些网站来测试是否生效，比如这个测试DNS泄漏的网站：  
https://browserleaks.com/dns   (查看DNS Leak Test列下面的测试，看看Your DNS Servers有没有出现境内的结果)   

## RULES_TTL:
该项设置的值大于0的时候生效，将`/data/force_ttl_rules.txt`里面指定的域名转发到指定的DNS服务器，并修改其TTL值为`RULES_TTL`。该功能仅对A记录和AAAA记录生效，其他记录请参考*进阶自定义示例*一节。该功能可以适用于多种场景，比如想实现DDNS的结果更实时一点，你可以把`RULES_TTL`设置为一个较低的值，然后把你的DDNS域名指定转发到对应的权威DNS服务器（也就是whois信息的NS服务器对应的IP地址，注意不要CNAME嵌套）即可。`force_ttl_rules`的规则格式为域名@服务器:端口，以下都是合法的格式：
```yaml
# whois info 03k.org:
# Name Servers:
# cold.dnspod.net(129.211.176.224)
# sunfish.dnspod.net(112.80.181.45)

cncheck.03k.org@129.211.176.224
cncheck.03k.org@129.211.176.224:53
cncheck.03k.org@129.211.176.224,112.80.181.45
cncheck.03k.org@129.211.176.224:53,112.80.181.45:53
cncheck.03k.org@129.211.176.224,112.80.181.45:53

# 注意，在该示例中，cncheck.03k.org和其子域名比如www.cncheck.03k.org都会被转发。
```  
此外，`RULES_TTL`功能也可以直接指定某个域名的A记录或者AAAA记录，或者“CNAME”到另一个域名。格式使用域名@@记录或者域名@@@记录，以下都是合法的格式：
```yaml
# 重定向www.qq.com
www.qq.com@@1.2.3.4
www.qq.com@@5.6.7.8 #可以指定多项记录
www.qq.com@@2404:6800:4008:c06::99

# CNAME www.qq.com 到qq.03k.org
www.qq.com@@qq.03k.org

# 注意，使用@@为子域名匹配，上述示例会匹配*.www.qq.com和www.qq.com


# 如果需要精确匹配，可以使用@@@：
www.qq.com@@@1.2.3.4
www.qq.com@@@2404:6800:4008:c06::99
www.qq.com@@@qq.03k.org
```

# 其他改进
- 新增`unbound_custom.conf`自定义配置文件，和`unbound.conf`模板分离，更新版本不会被覆盖删除。   
#### unbound_custom进阶自定义示例
1. 在企业内可能需要的一个功能，就是需要和AD域整合，转发指定域名到AD域服务器的方法：
打开`/data/unbound_custom.conf`编辑，滚动到最后几行，已经帮你准备好了配置示例，你只需要取消注释即可：
```yaml
#Active Directory Forward Example
# 在这个示例中，你公司的AD域名为company.local，有四台AD域DNS服务器。
forward-zone:
 name: "company.local"
 forward-no-cache:yes
 forward-addr: 10.111.222.11
 forward-addr: 10.111.222.12
 forward-addr: 10.111.222.13
 forward-addr: 10.111.222.14
```
注意：如果你开启了大陆分流功能，为了正确转发内网AD域名，请同时配合`RULES_TTL`功能使用。当然，此处是以AD域为场景进行举例，实际上你可以根据你的需求转发任意的域名。   

2. 添加微软KMS服务器SRV记录
```yaml
#Example of setting up SRV records for KMS server VLMCS.
#假设你的内网后缀是.lan，KMS服务器地址是192.168.1.2或者kms.ad.local

server:
    local-zone: "_vlmcs._tcp.lan." static
    local-data: "_vlmcs._tcp.lan. IN SRV 0 0 1688 kms.ad.local."
    local-data: "_vlmcs._tcp.lan. IN SRV 0 0 1688 192.168.1.2."

```
- 解决dnscrypt内网域名查询存在的问题，对容器构建dnscrypt配置模板加入预检测处理和添加更新源。相关issue：https://github.com/DNSCrypt/dnscrypt-resolvers/issues/813
- 优化`CNFALL`功能的实现方式，精简和修改mosdns可配置项，避免产生大量UDP请求
- 优化数据更新模块，提高下载成功率和避免重载处理冲突
- 更新了默认的`force_cn_list.txt`数据
- 优化mosdns处理模板流程，更简洁高效
- 优化了数据重载模块，相关txt配置或者数据更新后能尽快被应用无缝重载
- 新增`QUERY_TIME`调试项
- 改变`CN_TRACKER`功能的行为，走dnscrypt查询
- 改变`HTTP_FILE`功能的实现方式，删除httpd程序，使用修改后的mosdns内建httpd实现，减少空间占用和进程占用
