### DISCUSSION TITLE
替换指定IP段的解析结果为指定IP

### DISCUSSION THREAD

**Discussion by dudt** [kkkgo/PaoPaoDNS#57] [想法]
https://github.com/XIU2/CloudflareSpeedTest/discussions/317

**Comment by kkkgo** [comment]
做成功能的一个问题是，无法插入一个通用的流程，如果插入在境内DNS之后，有可能被污染，如果插入在境外DNS之后，那这个匹配IP段替换为IP的功能就仅限于境外IP，这是其次，主要问题是`black_hole`是要写死在mosdns.yaml里面的，并不能指定外部文件，这意味着你就算用脚本自动化测速，写入了IP，但仍然需要修改mosdns的配置文件，并且杀掉mosdns进程重新加载，这过程就有加载错误的配置文件导致无法启动DNS服务可能，那么就要要求你手动重启容器来生效配置，这么多自动化步骤下来，收益太低了。而`RULES_TTL `的实现是不需要修改mosdns的配置的，能保证运行过程中修改配置不会崩溃。

**Reply by kkkgo** [reply]
但也不是不能做，要写很多转换和错误检测。看看有没有同样需求的来回复一个吧，下个版本可以考虑一下。

**Reply by dudt** [reply]
我测试过自选和直接解析的得到的IP速度确实不一样，而且手动写入IP基本用个把月都没问题的，我在研究研究，谢谢大佬解答

**Reply by lr7skquo** [reply]
同样有这个需求。自家的网络（电信的家庭宽带）下载某些套了CF的网站的资源很慢，换了优选IP后，下载速度包括稳定性都有明显改善。
目前个人解决方案是用爱快的NAT将全部cf ipv4转发到优选IP，定期手工更新优选IP。

**Reply by kkkgo** [reply]
下个版本我尝试一下吧，需要改动的地方比较多。

**Comment by Sereinfy** [comment]
我有在用 目前是这个写法
```
  - tag: gfw_sequence
    type: sequence
    args:
      - exec: jump remote_sequence
      - exec: jump change_cdn_ip_cf #可以加个功能，把这一行注释掉=on
```
```
  - tag: change_cdn_ip_cf
      - matches:
          - resp_ip $cloudflare_ip
        exec: jump blackhole_cloudflare
```
