### DISCUSSION TITLE
mosdns分流逻辑不太理解，并不是以列表或返回IP进行分流的。

### DISCUSSION THREAD

**Discussion by 4thanks** [kkkgo/PaoPaoDNS#6] [问答和帮助] [answered]
force_cn_list.txt和force_nocn_list.txt，里面就只有几个域名。

我理解的常用分流是根据[Loyalsoldier/v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat/tree/release)列表分流。
或者根据返回的IP分流类似`local_unbound`返回非cnip转发至`$forward_unbound`：
```yaml
  - tag: 
    type: sequence
    args:
      - exec: $local_unbound
      - matches: resp_ip_mmdb $cnip CN
        exec: accept
      - exec: $forward_unbound
```
