### DISCUSSION TITLE
【更新日志】2023/11/03 PaoPaoDNS 增加custom_mod功能、custom_env功能、新缓存洗牌和新ADDINFO

### DISCUSSION THREAD

**Discussion by kkkgo** [kkkgo/PaoPaoDNS#61] [更新日志]
- 根据unbound新特性`redis-logical-db`调整redis配置。由于使用了新的缓存策略，因此不兼容旧的`redis_dns.rdb`数据文件，缓存文件新命名为`redis_dns_v2.rdb`。  
- 新增`SHUFFLE`选项：SHUFFLE 默认为`no`,设置为`yes`时，对解析的结果进行洗牌实现`Round-robin DNS`。
- 新增CUSTOM_FORWARD_TTL选项：该项设置的值大于0的时候生效，设定CUSTOM_FORWARD的ttl的最小值。该选项可以配合FAKEIP网关的低TTL使用，如果网关不经常重启，可以把TTL值设置更大一些以便缓存一段时间。  
- SOCKS5选项增加强制使用选项。 SOCKS5：为分流非CN IP的域名优先使用SOCKS5查询（如`10.10.10.8:7890`，强制使用socks5查询则加上@，比如`@10.10.10.8:7890`），但没有也能查，非必须项。仅在CNAUTO=yes时生效。SOCKS5初始化会有大概3分钟的延迟连接测试过程，期间的解析结果并非最优延迟。[FR 增加SOCKS5强制选项](https://github.com/kkkgo/PaoPaoDNS/discussions/51#discussioncomment-7184083)  
- 兼容低版本Linux内核内存检测。（https://github.com/kkkgo/PaoPaoDNS/discussions/48#discussioncomment-7136895 ）
- 自动根据内存容量限制核心使用。（ https://github.com/kkkgo/PaoPaoDNS/discussions/58#discussioncomment-7335704 ）
- 删除`unbound_custom.conf`forward-zone:示例。使用新增的`custom_mod`功能代替。
- 删除了两个失效的alpine软件源，屏蔽软件源更新连接错误。
- `debug.sh`增加更多调试信息。容器启动设置data目录777。（ https://github.com/kkkgo/PaoPaoDNS/discussions/52 https://github.com/kkkgo/PaoPaoDNS/discussions/55 https://github.com/kkkgo/PaoPaoDNS/discussions/53 ）
- 精简mosdns更低体积和内存占用。
# 调试信息更丰富的ADDINFO功能
旧版本的ADDINFO功能：(https://github.com/kkkgo/PaoPaoDNS/discussions/45)
新版本的ADDINFO可以显示多条信息，不仅是最终的返回信息。
```shell
dig www.qq.com @10.10.10.9 -p53
; <<>> DiG 9.18.19 <<>> www.qq.com @10.10.10.9 -p53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9741
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1200
;; QUESTION SECTION:
;www.qq.com.                    IN      A

;; ANSWER SECTION:
ins-r23tsuuf.ias.tencent-cloud.net. 116 IN A    121.14.77.201
ins-r23tsuuf.ias.tencent-cloud.net. 116 IN A    121.14.77.221
www.qq.com.             296     IN      CNAME   ins-r23tsuuf.ias.tencent-cloud.net.

;; ADDITIONAL SECTION:
20231103120928.469587410.addinfo.paopaodns. 297 IN TXT "Since 1ms From:mmdb CN IP"
20231103120930.408007333.addinfo.paopaodns. 117 IN TXT "Since 0ms From:respond mosdns cache"

;; Query time: 0 msec
;; SERVER: 10.10.10.9#53(10.10.10.9) (UDP)
;; WHEN: Fri Nov 03 04:09:32 UTC 2023
;; MSG SIZE  rcvd: 367
```
`Since 1ms From:mmdb CN IP`：说明是从本地递归缓存拿的结果。如果是第一次解析这个域名，延迟应该会更长。此处Since XXms代表从查这条记录请求开始到这个流程节点曾经用了多少时间，不代表本次请求用了多少时间。本次请求的时间可以用最后一条Since XXms。
`respond mosdns cache`: 说明是本次结果从mosdns缓存中直接取的。
更多类型信息：
`not_a_aaaa -> local_unbound`：非A/AAAA记录，经过了递归查询。
`not_a_aaaa -> forward_unbound`：非A/AAAA记录，经过了加密查询。
`forward -> {CUSTOM_FORWARD_SERVER}@{CUSTOM_FORWARD_PORT}`：经过了{CUSTOM_FORWARD自定义转发。
`nocn forward_unbound` ：经过了判定处理为非CN域名，转到加密查询。
`nocn forward_dnscrypt`：经过了判定处理为非CN域名，转到加密查询失败后再次查询。
`local_unbound`：经过了递归查询。
`force_ttl_rules`：TTL_RULES规则导致的结果。
`AUTO_FORWARD_CHECK forward_unbound PRIVATE`：开启AUTO_FORWARD_CHECK功能后检查到该域名属于内网域名，经过了再次验证。
`mmdb CN IP`：经过了CN域名判断。
`try_cn_fall` : 经过了CNFALL功能。
`cn_mark`:  经过了USE_MARK_DATA功能的CN域名判断。
`respond mosdns cache`：由mosdns缓存响应的查询。  
`USE_HOSTS` : 使用了USE_HOSTS功能导致的结果。
`Swap: env_key` ：使用了custom_mod的Swap功能导致的结果。
`Host: env_key` ：使用了custom_mod的Host功能导致的结果。
`[zone forward]` ： 使用了custom_mod的Zones功能导致的结果。

Reject类型提示信息
当域名的解析查询失败的时候，可能会有多种原因，调试信息仅返回最后失败的直接原因，你需要综合其他信息来判断。
- `END by f_force_dnscrypt_list/f_force_nocn_list.`  : 直接原因是dnscrypt查询失败，比如查询一个不存在的域名，递归查询失败，转移到dnscrypt，dnscrypt也查询失败，最终得到这个结果，又或者一开始该域名就是从`force_dnscrypt_list/force_nocn_list`指定查询的但最终失败。
- `END by f_local_unbound.`: 直接原因是递归查询失败，只有指定`force_recurse_list/force_cn_list`进行强制递归的域名才会有这个返回。
- `END by try_auto_check.` : 直接原因是同时开启了`CUSTOM_FORWARD`、`AUTO_FORWARD`、`AUTO_FORWARD_CHECK`功能的时候，该域名被检查出不存在，或者所有查询办法均没法通过`AUTO_FORWARD_CHECK`检查而终止`CUSTOM_FORWARD`转发。
- `END by block qtype 64/65.` : 屏蔽qtype 64/65记录类型。
- `END by IPv6=no.` : 因为设置了`IPv6=no`，所以拒绝了aaaa记录的查询。
- `END by IPv6=yes, force_dnscrypt_list/force_nocn_list block aaaa.` 因为设置了`IPv6=yes`，该域名位于force_dnscrypt_list/force_nocn_list被判断为非CN域名而被直接拒绝aaaa记录的查询。
- `END by IPv6=yes, MARK_DATA block aaaa.` 同上，由MARK_DATA数据判断为为非CN域名而被直接拒绝aaaa记录的查询。  
- `END by IPv6=yes,NO CN IP block aaaa.` 因为设置了`IPv6=yes`，该域名因被IP库判断为非CN域名而被直接拒绝aaaa记录的查询。
- `Process terminated due to no wanted answers , status: REFUSED` 没有得到和请求匹配的可用记录，并且DNS服务器返回了错误（比如不存在的域名），或者网络原因在流程终止后没有得到任何记录。    

Block类型提示信息
仅在IPv6相关选项作用下出现，提示`Records may exist, but blocked by PaoPaoDNS IPV6 option.`，表示被拦截了IPv6查询请求。因`IPV6=yes/only6`选项而被过滤的AAAA记录查询，该情况仅在IPv4记录存在的时候出现。

注：`force_nocn_list`是`force_dnscrypt_list`的旧版本名称，`force_cn_list`是`force_recurse_list`的旧版本名称。
# custom_mod功能和custom_env功能
- `custom_env.ini`可以自定义环境变量，会覆盖在容器在启动时的环境变量。在容器启动后修改该文件将会导致MosDNS重载，但在容器启动后修改的环境变量不会影响已经启动的其他组件。配置的格式为`key="value"`（注意英文双引号），错误格式的环境变量将会被忽略加载。容器版本更新不会覆盖该文件。该功能可以方便地修改环境变量而无需重新创建容器（ https://github.com/kkkgo/PaoPaoDNS/discussions/32#discussioncomment-7400849 ）。
- `custom_mod.yaml`可以自定义一些高级功能，参见下面的`custom_mod.yaml`文件说明。错误的配置可能导致服务运行异常。需要重启容器应用配置。容器版本更新不会覆盖该文件。   
**custom_mod.yaml配置说明**  
```yaml
# yaml配置格式请注意空格缩进和冒号，错误的配置将不会被加载。
# Zones可以配置指定域名转发。可以配置多组。
# 与`RULES_TLL`等功能不同，Zones配置的域名转发优先级默认最高，并且可以转发所有记录类型。
Zones:
 - zone: company.local
   dns: udp://10.10.10.3:53,udp://10.10.10.4:53
   ttl: 0
   seq: top
   socks5: no
# - zone: 此处填转发的域名。也可以是子域名，或者后缀。
#   dns: 可以逗号分隔指定多个DNS服务器、udp/tcp协议、端口。
#        指定超过3个DNS服务器将随机选择3个。
#   ttl: 指定该域名的最大ttl值。当设置非0的时候生效。
#        设置为0为不修改原来的ttl。
#   seq: top  #缺省选项，优先级最高，直接进行转发所有类型记录
#        top6 #与top一样但应用全局的IPv6设置
#        list #优先级最低，在匹配所有list后匹配
#   socks5: 可以配置为yes或者no，是否使用socks5代理来查询。
#           仅支持代理tcp协议的dns服务器。
 - zone: .corp
   dns: udp://10.10.10.3:53,udp://10.10.10.4:53
   ttl: 60
   seq: top6
   socks5: no
 - zone: ddns.example.com
   dns: tcp://172.64.32.176:53,tcp://108.162.192.176:53
   ttl: 3
   seq: list
   socks5: yes
# Swaps可以指定某个IP/CIDR段的解析结果替换为指定变量的结果。
# 以最终解析结果为准匹配。与Zones格式类似可以配置多组。
Swaps:
 - env_key: test_ip
   cidr_file: "/data/test_cidr.txt"
# env_key：配置指定变量的解析结果。可以配合custom_env.ini使用。
# cidr_file: 配置指定IP/CIDR段的文本文件。格式为每行一个IP/CIDR段。
# 注意：如果env_key或者cidr_file配置出错，容器日志会报错并忽略替换。
```
注：`Swaps`应用场景参考：[替换指定IP段的解析结果为指定IP](https://github.com/kkkgo/PaoPaoDNS/discussions/57 )

**Comment by Geilberton** [comment]
这个custom_mod是为了实现部份cidr地址段不走socks5么，而且还附带了自定义的dns，真是可喜可贺，这样就没必要在一个多需求的家庭网络中全部过透明代理了，非常感谢作者的努力 XD
不过为了行为管理和过滤统计还是用了个adgh作为上游，虽然我不用上，但是应该不少人都有这个需求的，再次感谢作者大佬
连custom_env也可以实现自由配置了，普天同庆 ：P

**Reply by kkkgo** [reply]
不是的，custom_mod的zones是自定义域名转发，swaps是匹配cidr结果替换成指定结果（比如用于CF优选IP）。
你说的绕过透明代理直接开两个DNS，然后dhcp不同客户端分配不同DNS就可以了。

**Reply by Geilberton** [reply]
噢，对不起，误解了，去看了下issue， 明白了 XD

**Comment by kkkgo** [comment]
2023/11/06 调整mosdns代码版本解决低版本linux内核兼容性 https://github.com/kkkgo/PaoPaoDNS/discussions/62#discussioncomment-7487459 ，无其他无更新。

**Comment by kkkgo** [comment]
2023/11/12 使用内建实现的curl替代系统curl，增加低版本linux内核兼容性和减少镜像体积，无其他更新。

**Comment by Edmondguo** [comment]
请教一下，关于 “Swaps应用场景参考：https://github.com/kkkgo/PaoPaoDNS/discussions/57”
是不是env_key填写跑出来的优选IP，或者在custom_env.ini里面添加 test_ip="优选IP"
cidr_file里面填写下面这些内容？
1.1.1.0/24
1.0.0.0/24
162.158.0.0/15
104.16.0.0/12
172.64.0.0/13

custom_env.ini示例里面2000::1 2002::2的意思是什么？

**Reply by kkkgo** [reply]
说明有注释：
```yaml
Swaps:
 - env_key: test_ip
   cidr_file: "/data/test_cidr.txt"
# env_key：配置指定变量的解析结果。可以配合custom_env.ini使用。
# cidr_file: 配置指定IP/CIDR段的文本文件。格式为每行一个IP/CIDR段。
# 注意：如果env_key或者cidr_file配置出错，容器日志会报错并忽略替换。
```

env_key填写你要替换IP的环境变量。比如你在custom_env.ini里面添加 test_ip="优选IP"。则填写test_ip。
cidr_file填写指定IP/CIDR段的文本文件。也就是把你上面那些东西写到一个txt文本里面去，然后这里填文本的文件路径。
custom_env.ini示例里面2000::1 2002::2的意思是什么？是IPv6地址。你可以替换成IPv4或者IPv6地址都可以。
