### DISCUSSION TITLE
dst address不停报错导致CPU占用率高

### DISCUSSION THREAD

**Discussion by tyycssy007** [kkkgo/PaoPaoDNS#62] [问答和帮助] [answered]
大佬，我昨晚更新了最新版本，运行了一晚后发现CPU占用率比较高，我的机器达到了50%以上，前个版本无此现象，排查日志发现不停报dst address出错
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/b0b05d31-38a6-47fa-ab1d-54fabfd14a2d)
运行debug数据如下：
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/b9a61c9f-05bf-4aa2-8d24-687d5dde8e32)
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/ddbbe8d6-9e66-4b1c-9426-0ee3d1ca90a0)
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/36695287-9eb6-40d1-80a1-9b6a5fb920c4)
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/7b6123e1-f161-4a23-9377-802df52f5c31)
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/2648f6e4-5365-46d5-b66c-ad0cebbbc1ab)
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/0d2a27e1-e1c4-44c0-9cb3-b093c56fd8c1)
烦请大佬指点，感谢

**Comment by kkkgo** [comment]
暂时没碰到，这个看到Linux内核版本比较低，开SAFEMODE=yes看看

**Reply by tyycssy007** [reply]
开SAFEMODE=yes依然报错，CPU占用率还是高。测试将CNAUTO=no就不报错了，CPU占用率也下来了，感觉应该是我这里分流出了问题。

**Reply by kkkgo** [reply]
看起来是编译的mosdns在你的环境里面出现了问题，是低版本的DSM系统？

**Reply by tyycssy007** [reply]
不是低版本的，已经是DSM7.2了

**Reply by kkkgo** [reply]
群晖的linux内核似乎是跟设备型号走的，3.10的内核应该是比较旧的设备

**Reply by kkkgo** [reply]
新建了一个ds3622xs+的DSM7虚拟机运行似乎没问题，内核是`Linux 4.4.180+ #42962 SMP Sat Sep 3 22:22:16 CST 2022 x86_64 GNU/Linux synology_broadwellnk_3622xs+`。是容器日志一启动就会报这个错误吗？

**Reply by kkkgo** [reply]
另外感觉可能也和网络有关系，你是用群晖自带的Docker面板创建的容器吗

**Reply by tyycssy007** [reply]
确实是容器一启动就报错，是根据您的博客上的命令行创建的容器，并没有使用群晖自带的Docker面板创建。

**Reply by kkkgo** [reply]
是什么型号群晖呢，我看能不能虚拟一个。
另外先试试群晖自带面板创建看看报不报错。

**Reply by tyycssy007** [reply]
型号是DS716+II，晚上我再测试一下用自带面板创建，感谢帮忙排查。

**Reply by tyycssy007** [reply]
最新测试下来使用群晖自带的面板创建还是报同样的错误

**Reply by kkkgo** [reply]
用面板创建，网络模式是bridge吗

**Reply by tyycssy007** [reply]
不是，网络模式是macvlan

**Reply by kkkgo** [reply]
用默认的bridge网络创建试试，可能就是macvlan有问题

**Reply by tyycssy007** [reply]
我测试一下看看吧

**Reply by tyycssy007** [reply]
使用bridge网络模式还是同样报错

**Reply by kkkgo** [reply]
谢谢测试，你拉一下`sliamb/testdns`镜像看看有什么日志报错

**Reply by tyycssy007** [reply]
测试结果如下图：
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/81d582f5-40d9-40be-9a90-1a94e3587fc5)

**Reply by tyycssy007** [reply]
上图是在macvlan网络模式下的测试的。

**Reply by kkkgo** [reply]
这个`docker run `命令好像没指定macvlan网络和IP吧？拉一下`sliamb/testdns2`，给指定个IP再试试，看看用这个IP当DNS会不会报错

**Reply by tyycssy007** [reply]
具体的命令行可以给我参考一下么，我是小白

**Reply by tyycssy007** [reply]
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/bf292312-a5e9-4461-84bf-860111b9b898)

**Reply by kkkgo** [reply]
好的，再用同样的方式，试试`sliamb/dnstest3`

**Reply by kkkgo** [reply]
你就直接用群晖的docker面板创建吧，映射一下53端口就行。然后用nslookup测试一下能不能查询DNS，日志有没有报错。

**Reply by tyycssy007** [reply]
测试了，同样报错，如图
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/35ebcfbf-ad74-44f6-ab9a-378dded2c320)

**Reply by tyycssy007** [reply]
刚测试了，一样的错误
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/1ad347d9-ac55-4a42-8bcd-ecb319c697b1)

**Reply by kkkgo** [reply]
好的，可以确认mosdns最新官方代码也会报错，你再试试`sliamb/testdns6`。

**Reply by tyycssy007** [reply]
依然报错，那应该是mosdns的问题了吧
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/baf9ea08-5d79-4a0a-9492-a6ece4b46529)

**Reply by kkkgo** [reply]
这个是回退了一个月的mosdns，还报错的话应该是网络环境有问题了，你之前是用命令行创建的macvlan吗？把创建的macvlan删掉用`docker network rm macvlan_eth0`命令，`macvlan_eth0`是你创建的macvlan名字，不知道的可以用`docker network ls`，再用群晖自带面板创建试试，选host模式。

**Reply by tyycssy007** [reply]
macvlan是用命令行创建的。使用群晖面板创建的host模式也是报错，不过我还没把macvlan删除，明天我再把macvlan删除后再用host模式测试一下
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/f01d6c72-1f40-4d18-99f4-d0ba5d80d8a0)

**Reply by tyycssy007** [reply]
刚刚有空将macvlan删除了，使用面板创建host模式，还是报错
![image](https://github.com/kkkgo/PaoPaoDNS/assets/146353004/7e14c09f-4912-4621-bddf-a39304b757d8)

**Reply by kkkgo** [reply]
再试试` sliamb/testdns7`，这是mosdns三月份的代码版本。

**Reply by tyycssy007** [reply]
这个版本终于不报错了，和前面测试一样用的macvlan模式

**Reply by kkkgo** [reply]
你分别试下这几个镜像哪个报错吧，感觉很接近了 ：
```shell
sliamb/testdns:0315 
sliamb/testdns:0316
sliamb/testdns:081301
sliamb/testdns:081302
sliamb/testdns:0831
```

**Reply by tyycssy007** [reply]
这五个里面只有最后一个0831是报错的

**Reply by kkkgo** [reply]
可以基本确定是mosdns的8月31日这个提交之后的问题了：https://github.com/IrineSistiana/mosdns/commit/98701bdf59c18a6482c9b12bbaf056f3276a84c5  

排除一下是我编译的问题，
现在你在当前目录新建`test.yaml`：
```yaml
log:
    file: ""
    level: debug
plugins:

  - tag: try_cn
    type: forward
    args:
      concurrent: 3
      upstreams:
        - addr: "udp://223.5.5.5"
        - addr: "udp://114.114.114.114"
        - addr: "udp://119.29.29.29"
  - tag: main_sequence
    type: sequence
    args:
        - exec: $try_cn
        - matches: has_wanted_ans
          exec: accept

  - tag: udp_server53
    type: udp_server
    args:
      entry: main_sequence
      listen: :53
  - tag: "tcp_server53"
    type: "tcp_server"
    args:
      entry: main_sequence
      listen: :53
      idle_timeout: 5
```
下载mosdns的编译好的版本：
最新版本：
https://github.com/IrineSistiana/mosdns/releases/download/v5.3.0/mosdns-linux-amd64.zip
3月份的版本：
https://github.com/IrineSistiana/mosdns/releases/download/v5.1.3/mosdns-linux-amd64.zip
，上传到群晖，执行：
`./mosdns start -c ./test.yaml`

按预期测试的话，应该是一个报错一个不报错。
